// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expected.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const claimReservedNode = `-- name: ClaimReservedNode :one
UPDATE nodes SET address = ?, status = ?
WHERE site_id = ? AND name = ? AND status = 'reserved'
RETURNING id, site_id, name, address, labels, roots, volumes, status, created_at, revoked_at, cordoned_at
`

type ClaimReservedNodeParams struct {
	Address string
	Status  string
	SiteID  int64
	Name    string
}

// Turns a "node add"-only row (status='reserved', no cert ever issued) into
// a claimed one, in place. Only matches rows still in 'reserved' status, so
// it cannot be used to steal an identity that already has a cert.
// Zero rows matched surfaces to Go as sql.ErrNoRows.
func (q *Queries) ClaimReservedNode(ctx context.Context, arg ClaimReservedNodeParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, claimReservedNode,
		arg.Address,
		arg.Status,
		arg.SiteID,
		arg.Name,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.Address,
		&i.Labels,
		&i.Roots,
		&i.Volumes,
		&i.Status,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.CordonedAt,
	)
	return i, err
}

const countDependents = `-- name: CountDependents :one
SELECT count(*) AS n FROM pack_bindings WHERE bound_component_id = ?
`

func (q *Queries) CountDependents(ctx context.Context, boundComponentID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDependents, boundComponentID)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComponent = `-- name: CreateComponent :one

INSERT INTO components (
    site_id, name, pack_name, pack_version, pack_revision,
    profile, params, drift_policy, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, site_id, name, pack_name, pack_version, pack_revision, profile, params, drift_policy, created_at, updated_at, previous_version, previous_revision, rollout_max_unavailable, rollout_canary, state, removal_keep_config, removal_purge_data, removal_purge_user, removing_at
`

type CreateComponentParams struct {
	SiteID       int64
	Name         string
	PackName     string
	PackVersion  string
	PackRevision int64
	Profile      string
	Params       string
	DriftPolicy  string
	CreatedAt    string
	UpdatedAt    string
}

// -- components ----------------------------------------------------------
func (q *Queries) CreateComponent(ctx context.Context, arg CreateComponentParams) (Component, error) {
	row := q.db.QueryRowContext(ctx, createComponent,
		arg.SiteID,
		arg.Name,
		arg.PackName,
		arg.PackVersion,
		arg.PackRevision,
		arg.Profile,
		arg.Params,
		arg.DriftPolicy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.PackName,
		&i.PackVersion,
		&i.PackRevision,
		&i.Profile,
		&i.Params,
		&i.DriftPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PreviousVersion,
		&i.PreviousRevision,
		&i.RolloutMaxUnavailable,
		&i.RolloutCanary,
		&i.State,
		&i.RemovalKeepConfig,
		&i.RemovalPurgeData,
		&i.RemovalPurgeUser,
		&i.RemovingAt,
	)
	return i, err
}

const createJoinToken = `-- name: CreateJoinToken :one

INSERT INTO join_tokens (
    site_id, token_hash, node_name, expires_at, max_uses, created_at, created_by
) VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, site_id, token_hash, node_name, expires_at, max_uses, used, revoked_at, created_at, created_by
`

type CreateJoinTokenParams struct {
	SiteID    int64
	TokenHash string
	NodeName  string
	ExpiresAt string
	MaxUses   int64
	CreatedAt string
	CreatedBy string
}

// -- join_tokens ---------------------------------------------------------
func (q *Queries) CreateJoinToken(ctx context.Context, arg CreateJoinTokenParams) (JoinToken, error) {
	row := q.db.QueryRowContext(ctx, createJoinToken,
		arg.SiteID,
		arg.TokenHash,
		arg.NodeName,
		arg.ExpiresAt,
		arg.MaxUses,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	var i JoinToken
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.TokenHash,
		&i.NodeName,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.Used,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const createPackBinding = `-- name: CreatePackBinding :one
INSERT INTO pack_bindings (component_id, require_name, bound_component_id, created_at)
VALUES (?, ?, ?, ?)
RETURNING id, component_id, require_name, bound_component_id, created_at
`

type CreatePackBindingParams struct {
	ComponentID      int64
	RequireName      string
	BoundComponentID int64
	CreatedAt        string
}

func (q *Queries) CreatePackBinding(ctx context.Context, arg CreatePackBindingParams) (PackBinding, error) {
	row := q.db.QueryRowContext(ctx, createPackBinding,
		arg.ComponentID,
		arg.RequireName,
		arg.BoundComponentID,
		arg.CreatedAt,
	)
	var i PackBinding
	err := row.Scan(
		&i.ID,
		&i.ComponentID,
		&i.RequireName,
		&i.BoundComponentID,
		&i.CreatedAt,
	)
	return i, err
}

const createRoleInstance = `-- name: CreateRoleInstance :one
INSERT INTO role_instances (component_id, role, node_id, ordinal, config_group_id, created_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, component_id, role, node_id, ordinal, config_group_id, created_at, facts, run_state
`

type CreateRoleInstanceParams struct {
	ComponentID   int64
	Role          string
	NodeID        int64
	Ordinal       int64
	ConfigGroupID sql.NullInt64
	CreatedAt     string
}

func (q *Queries) CreateRoleInstance(ctx context.Context, arg CreateRoleInstanceParams) (RoleInstance, error) {
	row := q.db.QueryRowContext(ctx, createRoleInstance,
		arg.ComponentID,
		arg.Role,
		arg.NodeID,
		arg.Ordinal,
		arg.ConfigGroupID,
		arg.CreatedAt,
	)
	var i RoleInstance
	err := row.Scan(
		&i.ID,
		&i.ComponentID,
		&i.Role,
		&i.NodeID,
		&i.Ordinal,
		&i.ConfigGroupID,
		&i.CreatedAt,
		&i.Facts,
		&i.RunState,
	)
	return i, err
}

const createSession = `-- name: CreateSession :exec

INSERT INTO sessions (token_hash, user_name, created_at, expires_at)
VALUES (?, ?, ?, ?)
`

type CreateSessionParams struct {
	TokenHash string
	UserName  string
	CreatedAt string
	ExpiresAt string
}

// -- sessions -----------------------------------------------------------
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.TokenHash,
		arg.UserName,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const createSite = `-- name: CreateSite :one


INSERT INTO sites (name, kind, labels, created_at)
VALUES (?, ?, ?, ?)
RETURNING id, name, kind, labels, created_at
`

type CreateSiteParams struct {
	Name      string
	Kind      string
	Labels    string
	CreatedAt string
}

// Queries for expected state (the part that MUST be backed up).
// See docs/design/07-persistence.md section 1.7.
//
// IMPORTANT: comments in this file must be ASCII only.
// sqlc strips comments by byte offset; multi-byte characters shift those
// offsets and silently corrupt the generated SQL (it produced identifiers
// like "INSEid" and "GetC" before we found this). The Chinese rationale for
// each query lives in the Go repository layer instead.
// A unit test enforces the ASCII constraint.
// -- sites ---------------------------------------------------------------
func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error) {
	row := q.db.QueryRowContext(ctx, createSite,
		arg.Name,
		arg.Kind,
		arg.Labels,
		arg.CreatedAt,
	)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Labels,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (name, password_hash, created_at, updated_at)
VALUES (?, ?, ?, ?)
RETURNING id, name, password_hash, created_at, updated_at
`

type CreateUserParams struct {
	Name         string
	PasswordHash string
	CreatedAt    string
	UpdatedAt    string
}

// -- users --------------------------------------------------------------
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Name,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComponent = `-- name: DeleteComponent :exec
DELETE FROM components WHERE id = ?
`

func (q *Queries) DeleteComponent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteComponent, id)
	return err
}

const deleteConfigGroup = `-- name: DeleteConfigGroup :exec
DELETE FROM config_groups WHERE component_id = ? AND role = ? AND name = ?
`

type DeleteConfigGroupParams struct {
	ComponentID int64
	Role        string
	Name        string
}

func (q *Queries) DeleteConfigGroup(ctx context.Context, arg DeleteConfigGroupParams) error {
	_, err := q.db.ExecContext(ctx, deleteConfigGroup, arg.ComponentID, arg.Role, arg.Name)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM nodes WHERE id = ?
`

func (q *Queries) DeleteNode(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteNode, id)
	return err
}

const deleteRoleInstance = `-- name: DeleteRoleInstance :exec
DELETE FROM role_instances WHERE id = ?
`

func (q *Queries) DeleteRoleInstance(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRoleInstance, id)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = ?
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, tokenHash)
	return err
}

const deleteSessionsOfUser = `-- name: DeleteSessionsOfUser :exec
DELETE FROM sessions WHERE user_name = ?
`

func (q *Queries) DeleteSessionsOfUser(ctx context.Context, userName string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsOfUser, userName)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE name = ?
`

func (q *Queries) DeleteUser(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, name)
	return err
}

const getComponent = `-- name: GetComponent :one
SELECT id, site_id, name, pack_name, pack_version, pack_revision, profile, params, drift_policy, created_at, updated_at, previous_version, previous_revision, rollout_max_unavailable, rollout_canary, state, removal_keep_config, removal_purge_data, removal_purge_user, removing_at FROM components WHERE id = ?
`

func (q *Queries) GetComponent(ctx context.Context, id int64) (Component, error) {
	row := q.db.QueryRowContext(ctx, getComponent, id)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.PackName,
		&i.PackVersion,
		&i.PackRevision,
		&i.Profile,
		&i.Params,
		&i.DriftPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PreviousVersion,
		&i.PreviousRevision,
		&i.RolloutMaxUnavailable,
		&i.RolloutCanary,
		&i.State,
		&i.RemovalKeepConfig,
		&i.RemovalPurgeData,
		&i.RemovalPurgeUser,
		&i.RemovingAt,
	)
	return i, err
}

const getComponentByName = `-- name: GetComponentByName :one
SELECT id, site_id, name, pack_name, pack_version, pack_revision, profile, params, drift_policy, created_at, updated_at, previous_version, previous_revision, rollout_max_unavailable, rollout_canary, state, removal_keep_config, removal_purge_data, removal_purge_user, removing_at FROM components WHERE site_id = ? AND name = ?
`

type GetComponentByNameParams struct {
	SiteID int64
	Name   string
}

func (q *Queries) GetComponentByName(ctx context.Context, arg GetComponentByNameParams) (Component, error) {
	row := q.db.QueryRowContext(ctx, getComponentByName, arg.SiteID, arg.Name)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.PackName,
		&i.PackVersion,
		&i.PackRevision,
		&i.Profile,
		&i.Params,
		&i.DriftPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PreviousVersion,
		&i.PreviousRevision,
		&i.RolloutMaxUnavailable,
		&i.RolloutCanary,
		&i.State,
		&i.RemovalKeepConfig,
		&i.RemovalPurgeData,
		&i.RemovalPurgeUser,
		&i.RemovingAt,
	)
	return i, err
}

const getConfigGroup = `-- name: GetConfigGroup :one
SELECT id, component_id, role, name, members, params, paths FROM config_groups
WHERE component_id = ? AND role = ? AND name = ?
`

type GetConfigGroupParams struct {
	ComponentID int64
	Role        string
	Name        string
}

func (q *Queries) GetConfigGroup(ctx context.Context, arg GetConfigGroupParams) (ConfigGroup, error) {
	row := q.db.QueryRowContext(ctx, getConfigGroup, arg.ComponentID, arg.Role, arg.Name)
	var i ConfigGroup
	err := row.Scan(
		&i.ID,
		&i.ComponentID,
		&i.Role,
		&i.Name,
		&i.Members,
		&i.Params,
		&i.Paths,
	)
	return i, err
}

const getJoinTokenByHash = `-- name: GetJoinTokenByHash :one
SELECT id, site_id, token_hash, node_name, expires_at, max_uses, used, revoked_at, created_at, created_by FROM join_tokens WHERE token_hash = ?
`

func (q *Queries) GetJoinTokenByHash(ctx context.Context, tokenHash string) (JoinToken, error) {
	row := q.db.QueryRowContext(ctx, getJoinTokenByHash, tokenHash)
	var i JoinToken
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.TokenHash,
		&i.NodeName,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.Used,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getNode = `-- name: GetNode :one
SELECT id, site_id, name, address, labels, roots, volumes, status, created_at, revoked_at, cordoned_at FROM nodes WHERE id = ?
`

func (q *Queries) GetNode(ctx context.Context, id int64) (Node, error) {
	row := q.db.QueryRowContext(ctx, getNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.Address,
		&i.Labels,
		&i.Roots,
		&i.Volumes,
		&i.Status,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.CordonedAt,
	)
	return i, err
}

const getNodeByName = `-- name: GetNodeByName :one
SELECT id, site_id, name, address, labels, roots, volumes, status, created_at, revoked_at, cordoned_at FROM nodes WHERE site_id = ? AND name = ?
`

type GetNodeByNameParams struct {
	SiteID int64
	Name   string
}

func (q *Queries) GetNodeByName(ctx context.Context, arg GetNodeByNameParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, getNodeByName, arg.SiteID, arg.Name)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.Address,
		&i.Labels,
		&i.Roots,
		&i.Volumes,
		&i.Status,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.CordonedAt,
	)
	return i, err
}

const getPackBinding = `-- name: GetPackBinding :one

SELECT id, component_id, require_name, bound_component_id, created_at FROM pack_bindings WHERE component_id = ? AND require_name = ?
`

type GetPackBindingParams struct {
	ComponentID int64
	RequireName string
}

// -- pack_bindings -------------------------------------------------------
func (q *Queries) GetPackBinding(ctx context.Context, arg GetPackBindingParams) (PackBinding, error) {
	row := q.db.QueryRowContext(ctx, getPackBinding, arg.ComponentID, arg.RequireName)
	var i PackBinding
	err := row.Scan(
		&i.ID,
		&i.ComponentID,
		&i.RequireName,
		&i.BoundComponentID,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleInstance = `-- name: GetRoleInstance :one
SELECT id, component_id, role, node_id, ordinal, config_group_id, created_at, facts, run_state FROM role_instances
WHERE component_id = ? AND role = ? AND node_id = ?
`

type GetRoleInstanceParams struct {
	ComponentID int64
	Role        string
	NodeID      int64
}

func (q *Queries) GetRoleInstance(ctx context.Context, arg GetRoleInstanceParams) (RoleInstance, error) {
	row := q.db.QueryRowContext(ctx, getRoleInstance, arg.ComponentID, arg.Role, arg.NodeID)
	var i RoleInstance
	err := row.Scan(
		&i.ID,
		&i.ComponentID,
		&i.Role,
		&i.NodeID,
		&i.Ordinal,
		&i.ConfigGroupID,
		&i.CreatedAt,
		&i.Facts,
		&i.RunState,
	)
	return i, err
}

const getSecret = `-- name: GetSecret :one

SELECT id, component_id, param, version, ciphertext, created_at, updated_at FROM secrets WHERE component_id = ? AND param = ?
`

type GetSecretParams struct {
	ComponentID int64
	Param       string
}

// -- secrets -------------------------------------------------------------
func (q *Queries) GetSecret(ctx context.Context, arg GetSecretParams) (Secret, error) {
	row := q.db.QueryRowContext(ctx, getSecret, arg.ComponentID, arg.Param)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.ComponentID,
		&i.Param,
		&i.Version,
		&i.Ciphertext,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT token_hash, user_name, created_at, expires_at FROM sessions WHERE token_hash = ?
`

func (q *Queries) GetSession(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, tokenHash)
	var i Session
	err := row.Scan(
		&i.TokenHash,
		&i.UserName,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getSite = `-- name: GetSite :one
SELECT id, name, kind, labels, created_at FROM sites WHERE id = ?
`

func (q *Queries) GetSite(ctx context.Context, id int64) (Site, error) {
	row := q.db.QueryRowContext(ctx, getSite, id)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Labels,
		&i.CreatedAt,
	)
	return i, err
}

const getSiteByName = `-- name: GetSiteByName :one
SELECT id, name, kind, labels, created_at FROM sites WHERE name = ?
`

func (q *Queries) GetSiteByName(ctx context.Context, name string) (Site, error) {
	row := q.db.QueryRowContext(ctx, getSiteByName, name)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Labels,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, name, password_hash, created_at, updated_at FROM users WHERE name = ?
`

func (q *Queries) GetUserByName(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByName, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWrappedDEK = `-- name: GetWrappedDEK :one

SELECT id, wrapped_dek, created_at FROM vault_keys WHERE id = 1
`

// -- vault_keys ----------------------------------------------------------
func (q *Queries) GetWrappedDEK(ctx context.Context) (VaultKey, error) {
	row := q.db.QueryRowContext(ctx, getWrappedDEK)
	var i VaultKey
	err := row.Scan(&i.ID, &i.WrappedDek, &i.CreatedAt)
	return i, err
}

const insertNode = `-- name: InsertNode :one
INSERT INTO nodes (site_id, name, address, labels, roots, volumes, status, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, site_id, name, address, labels, roots, volumes, status, created_at, revoked_at, cordoned_at
`

type InsertNodeParams struct {
	SiteID    int64
	Name      string
	Address   string
	Labels    string
	Roots     string
	Volumes   string
	Status    string
	CreatedAt string
}

// Plain insert, no ON CONFLICT: fails with SQLITE_CONSTRAINT_UNIQUE when
// (site_id, name) is already taken. Used by the join claim, which must
// reject rather than silently overwrite an existing identity.
func (q *Queries) InsertNode(ctx context.Context, arg InsertNodeParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, insertNode,
		arg.SiteID,
		arg.Name,
		arg.Address,
		arg.Labels,
		arg.Roots,
		arg.Volumes,
		arg.Status,
		arg.CreatedAt,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.Address,
		&i.Labels,
		&i.Roots,
		&i.Volumes,
		&i.Status,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.CordonedAt,
	)
	return i, err
}

const listComponents = `-- name: ListComponents :many
SELECT id, site_id, name, pack_name, pack_version, pack_revision, profile, params, drift_policy, created_at, updated_at, previous_version, previous_revision, rollout_max_unavailable, rollout_canary, state, removal_keep_config, removal_purge_data, removal_purge_user, removing_at FROM components WHERE site_id = ? ORDER BY name
`

func (q *Queries) ListComponents(ctx context.Context, siteID int64) ([]Component, error) {
	rows, err := q.db.QueryContext(ctx, listComponents, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Component{}
	for rows.Next() {
		var i Component
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Name,
			&i.PackName,
			&i.PackVersion,
			&i.PackRevision,
			&i.Profile,
			&i.Params,
			&i.DriftPolicy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PreviousVersion,
			&i.PreviousRevision,
			&i.RolloutMaxUnavailable,
			&i.RolloutCanary,
			&i.State,
			&i.RemovalKeepConfig,
			&i.RemovalPurgeData,
			&i.RemovalPurgeUser,
			&i.RemovingAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfigGroups = `-- name: ListConfigGroups :many
SELECT id, component_id, role, name, members, params, paths FROM config_groups WHERE component_id = ? ORDER BY role, name
`

func (q *Queries) ListConfigGroups(ctx context.Context, componentID int64) ([]ConfigGroup, error) {
	rows, err := q.db.QueryContext(ctx, listConfigGroups, componentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigGroup{}
	for rows.Next() {
		var i ConfigGroup
		if err := rows.Scan(
			&i.ID,
			&i.ComponentID,
			&i.Role,
			&i.Name,
			&i.Members,
			&i.Params,
			&i.Paths,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDependents = `-- name: ListDependents :many
SELECT c.name AS component, b.require_name
FROM pack_bindings b
JOIN components c ON c.id = b.component_id
WHERE b.bound_component_id = ?
ORDER BY c.name, b.require_name
`

type ListDependentsRow struct {
	Component   string
	RequireName string
}

// Names the components that depend on this one, plus which require slot binds
// them. A bare count cannot answer the only question the user actually has
// when a removal is refused: which ones, and do I still need them.
func (q *Queries) ListDependents(ctx context.Context, boundComponentID int64) ([]ListDependentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDependents, boundComponentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDependentsRow{}
	for rows.Next() {
		var i ListDependentsRow
		if err := rows.Scan(&i.Component, &i.RequireName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJoinTokens = `-- name: ListJoinTokens :many
SELECT id, site_id, token_hash, node_name, expires_at, max_uses, used, revoked_at, created_at, created_by FROM join_tokens WHERE site_id = ? ORDER BY id DESC
`

func (q *Queries) ListJoinTokens(ctx context.Context, siteID int64) ([]JoinToken, error) {
	rows, err := q.db.QueryContext(ctx, listJoinTokens, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JoinToken{}
	for rows.Next() {
		var i JoinToken
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.TokenHash,
			&i.NodeName,
			&i.ExpiresAt,
			&i.MaxUses,
			&i.Used,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodes = `-- name: ListNodes :many
SELECT id, site_id, name, address, labels, roots, volumes, status, created_at, revoked_at, cordoned_at FROM nodes WHERE site_id = ? ORDER BY name
`

func (q *Queries) ListNodes(ctx context.Context, siteID int64) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, listNodes, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Name,
			&i.Address,
			&i.Labels,
			&i.Roots,
			&i.Volumes,
			&i.Status,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.CordonedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackBindings = `-- name: ListPackBindings :many
SELECT id, component_id, require_name, bound_component_id, created_at FROM pack_bindings WHERE component_id = ? ORDER BY require_name
`

func (q *Queries) ListPackBindings(ctx context.Context, componentID int64) ([]PackBinding, error) {
	rows, err := q.db.QueryContext(ctx, listPackBindings, componentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PackBinding{}
	for rows.Next() {
		var i PackBinding
		if err := rows.Scan(
			&i.ID,
			&i.ComponentID,
			&i.RequireName,
			&i.BoundComponentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleInstances = `-- name: ListRoleInstances :many

SELECT id, component_id, role, node_id, ordinal, config_group_id, created_at, facts, run_state FROM role_instances WHERE component_id = ? ORDER BY role, ordinal
`

// -- role_instances ------------------------------------------------------
func (q *Queries) ListRoleInstances(ctx context.Context, componentID int64) ([]RoleInstance, error) {
	rows, err := q.db.QueryContext(ctx, listRoleInstances, componentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoleInstance{}
	for rows.Next() {
		var i RoleInstance
		if err := rows.Scan(
			&i.ID,
			&i.ComponentID,
			&i.Role,
			&i.NodeID,
			&i.Ordinal,
			&i.ConfigGroupID,
			&i.CreatedAt,
			&i.Facts,
			&i.RunState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleInstancesByNode = `-- name: ListRoleInstancesByNode :many
SELECT id, component_id, role, node_id, ordinal, config_group_id, created_at, facts, run_state FROM role_instances WHERE node_id = ?
`

func (q *Queries) ListRoleInstancesByNode(ctx context.Context, nodeID int64) ([]RoleInstance, error) {
	rows, err := q.db.QueryContext(ctx, listRoleInstancesByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoleInstance{}
	for rows.Next() {
		var i RoleInstance
		if err := rows.Scan(
			&i.ID,
			&i.ComponentID,
			&i.Role,
			&i.NodeID,
			&i.Ordinal,
			&i.ConfigGroupID,
			&i.CreatedAt,
			&i.Facts,
			&i.RunState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleInstancesByRole = `-- name: ListRoleInstancesByRole :many
SELECT id, component_id, role, node_id, ordinal, config_group_id, created_at, facts, run_state FROM role_instances
WHERE component_id = ? AND role = ?
ORDER BY ordinal
`

type ListRoleInstancesByRoleParams struct {
	ComponentID int64
	Role        string
}

func (q *Queries) ListRoleInstancesByRole(ctx context.Context, arg ListRoleInstancesByRoleParams) ([]RoleInstance, error) {
	rows, err := q.db.QueryContext(ctx, listRoleInstancesByRole, arg.ComponentID, arg.Role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoleInstance{}
	for rows.Next() {
		var i RoleInstance
		if err := rows.Scan(
			&i.ID,
			&i.ComponentID,
			&i.Role,
			&i.NodeID,
			&i.Ordinal,
			&i.ConfigGroupID,
			&i.CreatedAt,
			&i.Facts,
			&i.RunState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecrets = `-- name: ListSecrets :many
SELECT id, component_id, param, version, ciphertext, created_at, updated_at FROM secrets WHERE component_id = ? ORDER BY param
`

func (q *Queries) ListSecrets(ctx context.Context, componentID int64) ([]Secret, error) {
	rows, err := q.db.QueryContext(ctx, listSecrets, componentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Secret{}
	for rows.Next() {
		var i Secret
		if err := rows.Scan(
			&i.ID,
			&i.ComponentID,
			&i.Param,
			&i.Version,
			&i.Ciphertext,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSites = `-- name: ListSites :many
SELECT id, name, kind, labels, created_at FROM sites ORDER BY name
`

func (q *Queries) ListSites(ctx context.Context) ([]Site, error) {
	rows, err := q.db.QueryContext(ctx, listSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Site{}
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Labels,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, password_hash, created_at, updated_at FROM users ORDER BY name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxOrdinal = `-- name: MaxOrdinal :one
SELECT COALESCE(MAX(ordinal), -1) AS max_ordinal
FROM role_instances
WHERE component_id = ? AND role = ?
`

type MaxOrdinalParams struct {
	ComponentID int64
	Role        string
}

// Returns -1 when the role has no instances, so the first one gets 0.
// Do NOT use count(): ordinals may have holes and count() would collide
// with an already-used number. See ADR-0028.
func (q *Queries) MaxOrdinal(ctx context.Context, arg MaxOrdinalParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, maxOrdinal, arg.ComponentID, arg.Role)
	var max_ordinal interface{}
	err := row.Scan(&max_ordinal)
	return max_ordinal, err
}

const putSecret = `-- name: PutSecret :one
INSERT INTO secrets (component_id, param, version, ciphertext, created_at, updated_at)
VALUES (?, ?, 1, ?, ?, ?)
ON CONFLICT (component_id, param) DO UPDATE SET
    version    = secrets.version + 1,
    ciphertext = excluded.ciphertext,
    updated_at = excluded.updated_at
RETURNING id, component_id, param, version, ciphertext, created_at, updated_at
`

type PutSecretParams struct {
	ComponentID int64
	Param       string
	Ciphertext  []byte
	CreatedAt   string
	UpdatedAt   string
}

// First write stores version=1; rotation bumps it. The version participates
// in the spec digest, so rotation necessarily produces a new generation.
// See docs/design/16-secrets.md section 5.
func (q *Queries) PutSecret(ctx context.Context, arg PutSecretParams) (Secret, error) {
	row := q.db.QueryRowContext(ctx, putSecret,
		arg.ComponentID,
		arg.Param,
		arg.Ciphertext,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.ComponentID,
		&i.Param,
		&i.Version,
		&i.Ciphertext,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const putWrappedDEK = `-- name: PutWrappedDEK :exec
INSERT INTO vault_keys (id, wrapped_dek, created_at)
VALUES (1, ?, ?)
ON CONFLICT (id) DO UPDATE SET wrapped_dek = excluded.wrapped_dek
`

type PutWrappedDEKParams struct {
	WrappedDek []byte
	CreatedAt  string
}

func (q *Queries) PutWrappedDEK(ctx context.Context, arg PutWrappedDEKParams) error {
	_, err := q.db.ExecContext(ctx, putWrappedDEK, arg.WrappedDek, arg.CreatedAt)
	return err
}

const revokeJoinToken = `-- name: RevokeJoinToken :exec
UPDATE join_tokens SET revoked_at = ? WHERE id = ?
`

type RevokeJoinTokenParams struct {
	RevokedAt sql.NullString
	ID        int64
}

func (q *Queries) RevokeJoinToken(ctx context.Context, arg RevokeJoinTokenParams) error {
	_, err := q.db.ExecContext(ctx, revokeJoinToken, arg.RevokedAt, arg.ID)
	return err
}

const setComponentRollout = `-- name: SetComponentRollout :exec
UPDATE components
SET rollout_max_unavailable = ?, rollout_canary = ?, updated_at = ?
WHERE id = ?
`

type SetComponentRolloutParams struct {
	RolloutMaxUnavailable int64
	RolloutCanary         int64
	UpdatedAt             string
	ID                    int64
}

func (q *Queries) SetComponentRollout(ctx context.Context, arg SetComponentRolloutParams) error {
	_, err := q.db.ExecContext(ctx, setComponentRollout,
		arg.RolloutMaxUnavailable,
		arg.RolloutCanary,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const setComponentRunState = `-- name: SetComponentRunState :execrows
UPDATE role_instances SET run_state = ? WHERE component_id = ?
`

type SetComponentRunStateParams struct {
	RunState    string
	ComponentID int64
}

func (q *Queries) SetComponentRunState(ctx context.Context, arg SetComponentRunStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setComponentRunState, arg.RunState, arg.ComponentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setNodeCordoned = `-- name: SetNodeCordoned :exec
UPDATE nodes SET cordoned_at = ? WHERE id = ?
`

type SetNodeCordonedParams struct {
	CordonedAt sql.NullString
	ID         int64
}

func (q *Queries) SetNodeCordoned(ctx context.Context, arg SetNodeCordonedParams) error {
	_, err := q.db.ExecContext(ctx, setNodeCordoned, arg.CordonedAt, arg.ID)
	return err
}

const setNodeRevoked = `-- name: SetNodeRevoked :exec
UPDATE nodes SET revoked_at = ? WHERE id = ?
`

type SetNodeRevokedParams struct {
	RevokedAt sql.NullString
	ID        int64
}

func (q *Queries) SetNodeRevoked(ctx context.Context, arg SetNodeRevokedParams) error {
	_, err := q.db.ExecContext(ctx, setNodeRevoked, arg.RevokedAt, arg.ID)
	return err
}

const setNodeStatus = `-- name: SetNodeStatus :exec
UPDATE nodes SET status = ? WHERE id = ?
`

type SetNodeStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) SetNodeStatus(ctx context.Context, arg SetNodeStatusParams) error {
	_, err := q.db.ExecContext(ctx, setNodeStatus, arg.Status, arg.ID)
	return err
}

const setRoleInstanceConfigGroup = `-- name: SetRoleInstanceConfigGroup :exec
UPDATE role_instances SET config_group_id = ? WHERE id = ?
`

type SetRoleInstanceConfigGroupParams struct {
	ConfigGroupID sql.NullInt64
	ID            int64
}

func (q *Queries) SetRoleInstanceConfigGroup(ctx context.Context, arg SetRoleInstanceConfigGroupParams) error {
	_, err := q.db.ExecContext(ctx, setRoleInstanceConfigGroup, arg.ConfigGroupID, arg.ID)
	return err
}

const setRoleInstanceFacts = `-- name: SetRoleInstanceFacts :exec
UPDATE role_instances SET facts = ? WHERE id = ?
`

type SetRoleInstanceFactsParams struct {
	Facts string
	ID    int64
}

func (q *Queries) SetRoleInstanceFacts(ctx context.Context, arg SetRoleInstanceFactsParams) error {
	_, err := q.db.ExecContext(ctx, setRoleInstanceFacts, arg.Facts, arg.ID)
	return err
}

const setRoleInstanceRunState = `-- name: SetRoleInstanceRunState :exec
UPDATE role_instances SET run_state = ? WHERE id = ?
`

type SetRoleInstanceRunStateParams struct {
	RunState string
	ID       int64
}

func (q *Queries) SetRoleInstanceRunState(ctx context.Context, arg SetRoleInstanceRunStateParams) error {
	_, err := q.db.ExecContext(ctx, setRoleInstanceRunState, arg.RunState, arg.ID)
	return err
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users SET password_hash = ?, updated_at = ? WHERE name = ?
`

type SetUserPasswordParams struct {
	PasswordHash string
	UpdatedAt    string
	Name         string
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, setUserPassword, arg.PasswordHash, arg.UpdatedAt, arg.Name)
	return err
}

const startComponentRemoval = `-- name: StartComponentRemoval :exec
UPDATE components
SET state = ?,
    removal_keep_config = ?, removal_purge_data = ?, removal_purge_user = ?,
    removing_at = ?, updated_at = ?
WHERE id = ?
`

type StartComponentRemovalParams struct {
	State             string
	RemovalKeepConfig int64
	RemovalPurgeData  int64
	RemovalPurgeUser  int64
	RemovingAt        string
	UpdatedAt         string
	ID                int64
}

// Writes the lifecycle state and the three switches in one statement; see
// the Go wrapper for why they must not be written separately.
//
// The state is a bound parameter, not a literal: sqlc 1.31 STRIPS THE QUOTES
// off a string literal on the right-hand side of an UPDATE ... SET, turning
// SET state = removing into SET state = removing -- a column reference.
// It exits 0 while doing this. The failure only shows up at runtime as
// "no such column: removing".
func (q *Queries) StartComponentRemoval(ctx context.Context, arg StartComponentRemovalParams) error {
	_, err := q.db.ExecContext(ctx, startComponentRemoval,
		arg.State,
		arg.RemovalKeepConfig,
		arg.RemovalPurgeData,
		arg.RemovalPurgeUser,
		arg.RemovingAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateComponent = `-- name: UpdateComponent :one
UPDATE components SET
    pack_version      = ?,
    pack_revision     = ?,
    profile           = ?,
    params            = ?,
    drift_policy      = ?,
    previous_version  = ?,
    previous_revision = ?,
    updated_at        = ?
WHERE id = ?
RETURNING id, site_id, name, pack_name, pack_version, pack_revision, profile, params, drift_policy, created_at, updated_at, previous_version, previous_revision, rollout_max_unavailable, rollout_canary, state, removal_keep_config, removal_purge_data, removal_purge_user, removing_at
`

type UpdateComponentParams struct {
	PackVersion      string
	PackRevision     int64
	Profile          string
	Params           string
	DriftPolicy      string
	PreviousVersion  string
	PreviousRevision int64
	UpdatedAt        string
	ID               int64
}

func (q *Queries) UpdateComponent(ctx context.Context, arg UpdateComponentParams) (Component, error) {
	row := q.db.QueryRowContext(ctx, updateComponent,
		arg.PackVersion,
		arg.PackRevision,
		arg.Profile,
		arg.Params,
		arg.DriftPolicy,
		arg.PreviousVersion,
		arg.PreviousRevision,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.PackName,
		&i.PackVersion,
		&i.PackRevision,
		&i.Profile,
		&i.Params,
		&i.DriftPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PreviousVersion,
		&i.PreviousRevision,
		&i.RolloutMaxUnavailable,
		&i.RolloutCanary,
		&i.State,
		&i.RemovalKeepConfig,
		&i.RemovalPurgeData,
		&i.RemovalPurgeUser,
		&i.RemovingAt,
	)
	return i, err
}

const upsertConfigGroup = `-- name: UpsertConfigGroup :one

INSERT INTO config_groups (component_id, role, name, members, params, paths)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (component_id, role, name) DO UPDATE SET
    members = excluded.members,
    params  = excluded.params,
    paths   = excluded.paths
RETURNING id, component_id, role, name, members, params, paths
`

type UpsertConfigGroupParams struct {
	ComponentID int64
	Role        string
	Name        string
	Members     string
	Params      string
	Paths       string
}

// -- config_groups -------------------------------------------------------
func (q *Queries) UpsertConfigGroup(ctx context.Context, arg UpsertConfigGroupParams) (ConfigGroup, error) {
	row := q.db.QueryRowContext(ctx, upsertConfigGroup,
		arg.ComponentID,
		arg.Role,
		arg.Name,
		arg.Members,
		arg.Params,
		arg.Paths,
	)
	var i ConfigGroup
	err := row.Scan(
		&i.ID,
		&i.ComponentID,
		&i.Role,
		&i.Name,
		&i.Members,
		&i.Params,
		&i.Paths,
	)
	return i, err
}

const upsertNode = `-- name: UpsertNode :one

INSERT INTO nodes (site_id, name, address, labels, roots, volumes, status, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (site_id, name) DO UPDATE SET
    address = excluded.address,
    labels  = excluded.labels,
    roots   = excluded.roots,
    volumes = excluded.volumes,
    status  = excluded.status
RETURNING id, site_id, name, address, labels, roots, volumes, status, created_at, revoked_at, cordoned_at
`

type UpsertNodeParams struct {
	SiteID    int64
	Name      string
	Address   string
	Labels    string
	Roots     string
	Volumes   string
	Status    string
	CreatedAt string
}

// -- nodes ---------------------------------------------------------------
func (q *Queries) UpsertNode(ctx context.Context, arg UpsertNodeParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, upsertNode,
		arg.SiteID,
		arg.Name,
		arg.Address,
		arg.Labels,
		arg.Roots,
		arg.Volumes,
		arg.Status,
		arg.CreatedAt,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.Address,
		&i.Labels,
		&i.Roots,
		&i.Volumes,
		&i.Status,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.CordonedAt,
	)
	return i, err
}

const useJoinTokenIfAvailable = `-- name: UseJoinTokenIfAvailable :execrows
UPDATE join_tokens
SET used = used + 1
WHERE id = ? AND used < max_uses AND revoked_at IS NULL AND expires_at > ?
`

type UseJoinTokenIfAvailableParams struct {
	ID        int64
	ExpiresAt string
}

func (q *Queries) UseJoinTokenIfAvailable(ctx context.Context, arg UseJoinTokenIfAvailableParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, useJoinTokenIfAvailable, arg.ID, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
