// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type Audit struct {
	ID      int64
	At      string
	Actor   string
	Action  string
	Target  string
	PackRef string
	Result  string
	Detail  string
}

type Component struct {
	ID                    int64
	SiteID                int64
	Name                  string
	PackName              string
	PackVersion           string
	PackRevision          int64
	Profile               string
	Params                string
	DriftPolicy           string
	CreatedAt             string
	UpdatedAt             string
	PreviousVersion       string
	PreviousRevision      int64
	RolloutMaxUnavailable int64
	RolloutCanary         int64
	State                 string
	RemovalKeepConfig     int64
	RemovalPurgeData      int64
	RemovalPurgeUser      int64
	RemovingAt            string
}

type ConfigGroup struct {
	ID          int64
	ComponentID int64
	Role        string
	Name        string
	Members     string
	Params      string
	Paths       string
}

type DriftReport struct {
	ID             int64
	RoleInstanceID int64
	ResourceID     string
	Changes        string
	SeenAt         string
}

type Event struct {
	ID      int64
	At      string
	SiteID  sql.NullInt64
	Kind    string
	Subject string
	Payload string
}

type InstanceStatus struct {
	RoleInstanceID   int64
	Digest           string
	Generation       int64
	Result           string
	WorkloadState    string
	Health           string
	Detail           string
	ReportedAt       string
	WorkloadAction   string
	WorkloadActionAt string
	RolledBackFrom   string
	Restarts         int64
	Removed          int64
	RetainedPaths    string
}

type JoinToken struct {
	ID        int64
	SiteID    int64
	TokenHash string
	NodeName  string
	ExpiresAt string
	MaxUses   int64
	Used      int64
	RevokedAt sql.NullString
	CreatedAt string
	CreatedBy string
}

type Node struct {
	ID         int64
	SiteID     int64
	Name       string
	Address    string
	Labels     string
	Roots      string
	Volumes    string
	Status     string
	CreatedAt  string
	RevokedAt  sql.NullString
	CordonedAt sql.NullString
}

type NodeFact struct {
	NodeID       int64
	Facts        string
	Capabilities string
	CollectedAt  string
}

type NodeOrphan struct {
	NodeID           int64
	InstanceKey      string
	FirstSeenAt      string
	LastSeenAt       string
	Paths            string
	PurgeRequestedAt string
}

type PackBinding struct {
	ID               int64
	ComponentID      int64
	RequireName      string
	BoundComponentID int64
	CreatedAt        string
}

type RoleInstance struct {
	ID            int64
	ComponentID   int64
	Role          string
	NodeID        int64
	Ordinal       int64
	ConfigGroupID sql.NullInt64
	CreatedAt     string
	Facts         string
	RunState      string
}

type Rollout struct {
	ID          int64
	ComponentID int64
	State       string
	Reason      string
	StartedAt   string
	EndedAt     sql.NullString
	FromVersion string
	ToVersion   string
	Kind        string
}

type RolloutBatch struct {
	ID              int64
	RolloutID       int64
	Seq             int64
	Targets         string
	State           string
	Stage           int64
	Role            string
	ReleasedAt      string
	HealthySince    string
	RestartBaseline string
}

type Secret struct {
	ID          int64
	ComponentID int64
	Param       string
	Version     int64
	Ciphertext  []byte
	CreatedAt   string
	UpdatedAt   string
}

type Session struct {
	TokenHash string
	UserName  string
	CreatedAt string
	ExpiresAt string
}

type Site struct {
	ID        int64
	Name      string
	Kind      string
	Labels    string
	CreatedAt string
}

type Suppression struct {
	ID             int64
	RoleInstanceID int64
	ResourceID     string
	Reason         string
	CreatedBy      string
	CreatedAt      string
	ExpiresAt      string
}

type User struct {
	ID           int64
	Name         string
	PasswordHash string
	CreatedAt    string
	UpdatedAt    string
}

type VaultKey struct {
	ID         int64
	WrappedDek []byte
	CreatedAt  string
}
