// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: observed.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const activeRollout = `-- name: ActiveRollout :one
SELECT id, component_id, state, reason, started_at, ended_at, from_version, to_version, kind FROM rollouts
WHERE component_id = ? AND state IN ('running', 'paused', 'halted')
ORDER BY started_at DESC, id DESC LIMIT 1
`

func (q *Queries) ActiveRollout(ctx context.Context, componentID int64) (Rollout, error) {
	row := q.db.QueryRowContext(ctx, activeRollout, componentID)
	var i Rollout
	err := row.Scan(
		&i.ID,
		&i.ComponentID,
		&i.State,
		&i.Reason,
		&i.StartedAt,
		&i.EndedAt,
		&i.FromVersion,
		&i.ToVersion,
		&i.Kind,
	)
	return i, err
}

const appendAudit = `-- name: AppendAudit :exec
INSERT INTO audit (at, actor, action, target, pack_ref, result, detail)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type AppendAuditParams struct {
	At      string
	Actor   string
	Action  string
	Target  string
	PackRef string
	Result  string
	Detail  string
}

func (q *Queries) AppendAudit(ctx context.Context, arg AppendAuditParams) error {
	_, err := q.db.ExecContext(ctx, appendAudit,
		arg.At,
		arg.Actor,
		arg.Action,
		arg.Target,
		arg.PackRef,
		arg.Result,
		arg.Detail,
	)
	return err
}

const appendEvent = `-- name: AppendEvent :exec
INSERT INTO events (at, site_id, kind, subject, payload)
VALUES (?, ?, ?, ?, ?)
`

type AppendEventParams struct {
	At      string
	SiteID  sql.NullInt64
	Kind    string
	Subject string
	Payload string
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) error {
	_, err := q.db.ExecContext(ctx, appendEvent,
		arg.At,
		arg.SiteID,
		arg.Kind,
		arg.Subject,
		arg.Payload,
	)
	return err
}

const clearDrift = `-- name: ClearDrift :exec
DELETE FROM drift_reports WHERE role_instance_id = ?
`

func (q *Queries) ClearDrift(ctx context.Context, roleInstanceID int64) error {
	_, err := q.db.ExecContext(ctx, clearDrift, roleInstanceID)
	return err
}

const countNodeOrphans = `-- name: CountNodeOrphans :one
SELECT count(*) FROM node_orphans WHERE node_id = ?
`

func (q *Queries) CountNodeOrphans(ctx context.Context, nodeID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNodeOrphans, nodeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRollout = `-- name: CreateRollout :one

INSERT INTO rollouts (component_id, state, reason, started_at, from_version, to_version, kind)
VALUES (?, ?, '', ?, ?, ?, ?)
RETURNING id, component_id, state, reason, started_at, ended_at, from_version, to_version, kind
`

type CreateRolloutParams struct {
	ComponentID int64
	State       string
	StartedAt   string
	FromVersion string
	ToVersion   string
	Kind        string
}

// -- rollouts ------------------------------------------------------------
func (q *Queries) CreateRollout(ctx context.Context, arg CreateRolloutParams) (Rollout, error) {
	row := q.db.QueryRowContext(ctx, createRollout,
		arg.ComponentID,
		arg.State,
		arg.StartedAt,
		arg.FromVersion,
		arg.ToVersion,
		arg.Kind,
	)
	var i Rollout
	err := row.Scan(
		&i.ID,
		&i.ComponentID,
		&i.State,
		&i.Reason,
		&i.StartedAt,
		&i.EndedAt,
		&i.FromVersion,
		&i.ToVersion,
		&i.Kind,
	)
	return i, err
}

const createRolloutBatch = `-- name: CreateRolloutBatch :one

INSERT INTO rollout_batches (rollout_id, seq, stage, role, targets, state)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, rollout_id, seq, targets, state, stage, role, released_at, healthy_since, restart_baseline
`

type CreateRolloutBatchParams struct {
	RolloutID int64
	Seq       int64
	Stage     int64
	Role      string
	Targets   string
	State     string
}

// -- rollout_batches ------------------------------------------------------
func (q *Queries) CreateRolloutBatch(ctx context.Context, arg CreateRolloutBatchParams) (RolloutBatch, error) {
	row := q.db.QueryRowContext(ctx, createRolloutBatch,
		arg.RolloutID,
		arg.Seq,
		arg.Stage,
		arg.Role,
		arg.Targets,
		arg.State,
	)
	var i RolloutBatch
	err := row.Scan(
		&i.ID,
		&i.RolloutID,
		&i.Seq,
		&i.Targets,
		&i.State,
		&i.Stage,
		&i.Role,
		&i.ReleasedAt,
		&i.HealthySince,
		&i.RestartBaseline,
	)
	return i, err
}

const createSuppression = `-- name: CreateSuppression :one
INSERT INTO suppressions (
    role_instance_id, resource_id, reason, created_by, created_at, expires_at
) VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, role_instance_id, resource_id, reason, created_by, created_at, expires_at
`

type CreateSuppressionParams struct {
	RoleInstanceID int64
	ResourceID     string
	Reason         string
	CreatedBy      string
	CreatedAt      string
	ExpiresAt      string
}

func (q *Queries) CreateSuppression(ctx context.Context, arg CreateSuppressionParams) (Suppression, error) {
	row := q.db.QueryRowContext(ctx, createSuppression,
		arg.RoleInstanceID,
		arg.ResourceID,
		arg.Reason,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i Suppression
	err := row.Scan(
		&i.ID,
		&i.RoleInstanceID,
		&i.ResourceID,
		&i.Reason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteNodeOrphansNotIn = `-- name: DeleteNodeOrphansNotIn :exec
DELETE FROM node_orphans
WHERE node_id = ? AND last_seen_at <> ?
`

type DeleteNodeOrphansNotInParams struct {
	NodeID     int64
	LastSeenAt string
}

// Rows not touched by this round are stale. Compare with <> rather than <:
// < assumes the clock strictly advances, and it does not have to. If the
// clock steps backwards (NTP), rows stamped in the future are never < the
// current stamp and would survive forever. <> means "not written by this
// round", which is the actual intent and holds whatever the clock does.
func (q *Queries) DeleteNodeOrphansNotIn(ctx context.Context, arg DeleteNodeOrphansNotInParams) error {
	_, err := q.db.ExecContext(ctx, deleteNodeOrphansNotIn, arg.NodeID, arg.LastSeenAt)
	return err
}

const getInstanceStatus = `-- name: GetInstanceStatus :one
SELECT role_instance_id, digest, generation, result, workload_state, health, detail, reported_at, workload_action, workload_action_at, rolled_back_from, restarts, removed, retained_paths FROM instance_status WHERE role_instance_id = ?
`

func (q *Queries) GetInstanceStatus(ctx context.Context, roleInstanceID int64) (InstanceStatus, error) {
	row := q.db.QueryRowContext(ctx, getInstanceStatus, roleInstanceID)
	var i InstanceStatus
	err := row.Scan(
		&i.RoleInstanceID,
		&i.Digest,
		&i.Generation,
		&i.Result,
		&i.WorkloadState,
		&i.Health,
		&i.Detail,
		&i.ReportedAt,
		&i.WorkloadAction,
		&i.WorkloadActionAt,
		&i.RolledBackFrom,
		&i.Restarts,
		&i.Removed,
		&i.RetainedPaths,
	)
	return i, err
}

const getNodeFacts = `-- name: GetNodeFacts :one
SELECT node_id, facts, capabilities, collected_at FROM node_facts WHERE node_id = ?
`

func (q *Queries) GetNodeFacts(ctx context.Context, nodeID int64) (NodeFact, error) {
	row := q.db.QueryRowContext(ctx, getNodeFacts, nodeID)
	var i NodeFact
	err := row.Scan(
		&i.NodeID,
		&i.Facts,
		&i.Capabilities,
		&i.CollectedAt,
	)
	return i, err
}

const getRollout = `-- name: GetRollout :one
SELECT id, component_id, state, reason, started_at, ended_at, from_version, to_version, kind FROM rollouts WHERE id = ?
`

func (q *Queries) GetRollout(ctx context.Context, id int64) (Rollout, error) {
	row := q.db.QueryRowContext(ctx, getRollout, id)
	var i Rollout
	err := row.Scan(
		&i.ID,
		&i.ComponentID,
		&i.State,
		&i.Reason,
		&i.StartedAt,
		&i.EndedAt,
		&i.FromVersion,
		&i.ToVersion,
		&i.Kind,
	)
	return i, err
}

const listAllNodeOrphans = `-- name: ListAllNodeOrphans :many
SELECT node_id, instance_key, first_seen_at, last_seen_at, paths, purge_requested_at FROM node_orphans ORDER BY node_id, instance_key
`

func (q *Queries) ListAllNodeOrphans(ctx context.Context) ([]NodeOrphan, error) {
	rows, err := q.db.QueryContext(ctx, listAllNodeOrphans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeOrphan{}
	for rows.Next() {
		var i NodeOrphan
		if err := rows.Scan(
			&i.NodeID,
			&i.InstanceKey,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.Paths,
			&i.PurgeRequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAudit = `-- name: ListAudit :many
SELECT id, at, actor, "action", target, pack_ref, result, detail FROM audit ORDER BY at DESC, id DESC LIMIT ?
`

func (q *Queries) ListAudit(ctx context.Context, limit int64) ([]Audit, error) {
	rows, err := q.db.QueryContext(ctx, listAudit, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Audit{}
	for rows.Next() {
		var i Audit
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.Actor,
			&i.Action,
			&i.Target,
			&i.PackRef,
			&i.Result,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDriftByComponent = `-- name: ListDriftByComponent :many
SELECT d.id, d.role_instance_id, d.resource_id, d.changes, d.seen_at FROM drift_reports d
JOIN role_instances ri ON ri.id = d.role_instance_id
WHERE ri.component_id = ?
ORDER BY d.role_instance_id, d.resource_id
`

func (q *Queries) ListDriftByComponent(ctx context.Context, componentID int64) ([]DriftReport, error) {
	rows, err := q.db.QueryContext(ctx, listDriftByComponent, componentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DriftReport{}
	for rows.Next() {
		var i DriftReport
		if err := rows.Scan(
			&i.ID,
			&i.RoleInstanceID,
			&i.ResourceID,
			&i.Changes,
			&i.SeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT id, at, site_id, kind, subject, payload FROM events
WHERE site_id = ?
ORDER BY at DESC, id DESC
LIMIT ?
`

type ListEventsParams struct {
	SiteID sql.NullInt64
	Limit  int64
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents, arg.SiteID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.SiteID,
			&i.Kind,
			&i.Subject,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstanceStatusByComponent = `-- name: ListInstanceStatusByComponent :many
SELECT s.role_instance_id, s.digest, s.generation, s.result, s.workload_state, s.health, s.detail, s.reported_at, s.workload_action, s.workload_action_at, s.rolled_back_from, s.restarts, s.removed, s.retained_paths FROM instance_status s
JOIN role_instances ri ON ri.id = s.role_instance_id
WHERE ri.component_id = ?
`

func (q *Queries) ListInstanceStatusByComponent(ctx context.Context, componentID int64) ([]InstanceStatus, error) {
	rows, err := q.db.QueryContext(ctx, listInstanceStatusByComponent, componentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstanceStatus{}
	for rows.Next() {
		var i InstanceStatus
		if err := rows.Scan(
			&i.RoleInstanceID,
			&i.Digest,
			&i.Generation,
			&i.Result,
			&i.WorkloadState,
			&i.Health,
			&i.Detail,
			&i.ReportedAt,
			&i.WorkloadAction,
			&i.WorkloadActionAt,
			&i.RolledBackFrom,
			&i.Restarts,
			&i.Removed,
			&i.RetainedPaths,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeOrphans = `-- name: ListNodeOrphans :many
SELECT node_id, instance_key, first_seen_at, last_seen_at, paths, purge_requested_at FROM node_orphans WHERE node_id = ? ORDER BY instance_key
`

func (q *Queries) ListNodeOrphans(ctx context.Context, nodeID int64) ([]NodeOrphan, error) {
	rows, err := q.db.QueryContext(ctx, listNodeOrphans, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeOrphan{}
	for rows.Next() {
		var i NodeOrphan
		if err := rows.Scan(
			&i.NodeID,
			&i.InstanceKey,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.Paths,
			&i.PurgeRequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrphanPurges = `-- name: ListOrphanPurges :many
SELECT instance_key FROM node_orphans
WHERE node_id = ? AND length(purge_requested_at) > 0
ORDER BY instance_key
`

// length(...) > 0 rather than != ”: sqlc 1.31 strips the quotes off a
// string literal here too, leaving a syntax error. Same trap as the
// UPDATE ... SET case in expected.sql.
func (q *Queries) ListOrphanPurges(ctx context.Context, nodeID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listOrphanPurges, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var instance_key string
		if err := rows.Scan(&instance_key); err != nil {
			return nil, err
		}
		items = append(items, instance_key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolloutBatches = `-- name: ListRolloutBatches :many
SELECT id, rollout_id, seq, targets, state, stage, role, released_at, healthy_since, restart_baseline FROM rollout_batches WHERE rollout_id = ? ORDER BY seq
`

func (q *Queries) ListRolloutBatches(ctx context.Context, rolloutID int64) ([]RolloutBatch, error) {
	rows, err := q.db.QueryContext(ctx, listRolloutBatches, rolloutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RolloutBatch{}
	for rows.Next() {
		var i RolloutBatch
		if err := rows.Scan(
			&i.ID,
			&i.RolloutID,
			&i.Seq,
			&i.Targets,
			&i.State,
			&i.Stage,
			&i.Role,
			&i.ReleasedAt,
			&i.HealthySince,
			&i.RestartBaseline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRollouts = `-- name: ListRollouts :many
SELECT id, component_id, state, reason, started_at, ended_at, from_version, to_version, kind FROM rollouts WHERE component_id = ? ORDER BY started_at DESC, id DESC LIMIT ?
`

type ListRolloutsParams struct {
	ComponentID int64
	Limit       int64
}

func (q *Queries) ListRollouts(ctx context.Context, arg ListRolloutsParams) ([]Rollout, error) {
	rows, err := q.db.QueryContext(ctx, listRollouts, arg.ComponentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rollout{}
	for rows.Next() {
		var i Rollout
		if err := rows.Scan(
			&i.ID,
			&i.ComponentID,
			&i.State,
			&i.Reason,
			&i.StartedAt,
			&i.EndedAt,
			&i.FromVersion,
			&i.ToVersion,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuppressionsByComponent = `-- name: ListSuppressionsByComponent :many
SELECT s.id, s.role_instance_id, s.resource_id, s.reason, s.created_by, s.created_at, s.expires_at FROM suppressions s
JOIN role_instances ri ON ri.id = s.role_instance_id
WHERE ri.component_id = ? AND s.expires_at > ?
ORDER BY s.role_instance_id, s.resource_id
`

type ListSuppressionsByComponentParams struct {
	ComponentID int64
	ExpiresAt   string
}

func (q *Queries) ListSuppressionsByComponent(ctx context.Context, arg ListSuppressionsByComponentParams) ([]Suppression, error) {
	rows, err := q.db.QueryContext(ctx, listSuppressionsByComponent, arg.ComponentID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Suppression{}
	for rows.Next() {
		var i Suppression
		if err := rows.Scan(
			&i.ID,
			&i.RoleInstanceID,
			&i.ResourceID,
			&i.Reason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneSuppressions = `-- name: PruneSuppressions :exec
DELETE FROM suppressions WHERE expires_at <= ?
`

func (q *Queries) PruneSuppressions(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, pruneSuppressions, expiresAt)
	return err
}

const releaseRolloutBatch = `-- name: ReleaseRolloutBatch :exec
UPDATE rollout_batches SET state = ?, released_at = ? WHERE id = ?
`

type ReleaseRolloutBatchParams struct {
	State      string
	ReleasedAt string
	ID         int64
}

func (q *Queries) ReleaseRolloutBatch(ctx context.Context, arg ReleaseRolloutBatchParams) error {
	_, err := q.db.ExecContext(ctx, releaseRolloutBatch, arg.State, arg.ReleasedAt, arg.ID)
	return err
}

const requestOrphanPurge = `-- name: RequestOrphanPurge :execrows
UPDATE node_orphans SET purge_requested_at = ?
WHERE node_id = ? AND instance_key = ?
`

type RequestOrphanPurgeParams struct {
	PurgeRequestedAt string
	NodeID           int64
	InstanceKey      string
}

func (q *Queries) RequestOrphanPurge(ctx context.Context, arg RequestOrphanPurgeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, requestOrphanPurge, arg.PurgeRequestedAt, arg.NodeID, arg.InstanceKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setRolloutBatchGate = `-- name: SetRolloutBatchGate :exec
UPDATE rollout_batches
SET healthy_since = ?, restart_baseline = ?
WHERE id = ?
`

type SetRolloutBatchGateParams struct {
	HealthySince    string
	RestartBaseline string
	ID              int64
}

func (q *Queries) SetRolloutBatchGate(ctx context.Context, arg SetRolloutBatchGateParams) error {
	_, err := q.db.ExecContext(ctx, setRolloutBatchGate, arg.HealthySince, arg.RestartBaseline, arg.ID)
	return err
}

const setRolloutBatchState = `-- name: SetRolloutBatchState :exec
UPDATE rollout_batches SET state = ? WHERE id = ?
`

type SetRolloutBatchStateParams struct {
	State string
	ID    int64
}

func (q *Queries) SetRolloutBatchState(ctx context.Context, arg SetRolloutBatchStateParams) error {
	_, err := q.db.ExecContext(ctx, setRolloutBatchState, arg.State, arg.ID)
	return err
}

const setRolloutState = `-- name: SetRolloutState :exec
UPDATE rollouts SET state = ?, reason = ?, ended_at = ? WHERE id = ?
`

type SetRolloutStateParams struct {
	State   string
	Reason  string
	EndedAt sql.NullString
	ID      int64
}

func (q *Queries) SetRolloutState(ctx context.Context, arg SetRolloutStateParams) error {
	_, err := q.db.ExecContext(ctx, setRolloutState,
		arg.State,
		arg.Reason,
		arg.EndedAt,
		arg.ID,
	)
	return err
}

const upsertDriftReport = `-- name: UpsertDriftReport :exec
INSERT INTO drift_reports (role_instance_id, resource_id, changes, seen_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (role_instance_id, resource_id) DO UPDATE SET
    changes = excluded.changes,
    seen_at = excluded.seen_at
`

type UpsertDriftReportParams struct {
	RoleInstanceID int64
	ResourceID     string
	Changes        string
	SeenAt         string
}

func (q *Queries) UpsertDriftReport(ctx context.Context, arg UpsertDriftReportParams) error {
	_, err := q.db.ExecContext(ctx, upsertDriftReport,
		arg.RoleInstanceID,
		arg.ResourceID,
		arg.Changes,
		arg.SeenAt,
	)
	return err
}

const upsertInstanceStatus = `-- name: UpsertInstanceStatus :exec

INSERT INTO instance_status (
    role_instance_id, digest, generation, result,
    workload_state, workload_action, workload_action_at, rolled_back_from,
    health, detail, reported_at, restarts, removed, retained_paths
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (role_instance_id) DO UPDATE SET
    digest          = excluded.digest,
    generation      = excluded.generation,
    result          = excluded.result,
    workload_state  = excluded.workload_state,
    workload_action = excluded.workload_action,
    workload_action_at = excluded.workload_action_at,
    rolled_back_from = excluded.rolled_back_from,
    health          = excluded.health,
    detail          = excluded.detail,
    reported_at     = excluded.reported_at,
    restarts        = excluded.restarts,
    removed         = excluded.removed,
    retained_paths  = excluded.retained_paths
`

type UpsertInstanceStatusParams struct {
	RoleInstanceID   int64
	Digest           string
	Generation       int64
	Result           string
	WorkloadState    string
	WorkloadAction   string
	WorkloadActionAt string
	RolledBackFrom   string
	Health           string
	Detail           string
	ReportedAt       string
	Restarts         int64
	Removed          int64
	RetainedPaths    string
}

// Observed state: what mechlet reports back.
//
// ASCII ONLY. sqlc silently corrupts identifiers when a query file contains
// non-ASCII bytes -- and it exits 0 while doing so. See store_test.go
// (TestQueryFilesAreASCII). Chinese commentary belongs in the Go code.
func (q *Queries) UpsertInstanceStatus(ctx context.Context, arg UpsertInstanceStatusParams) error {
	_, err := q.db.ExecContext(ctx, upsertInstanceStatus,
		arg.RoleInstanceID,
		arg.Digest,
		arg.Generation,
		arg.Result,
		arg.WorkloadState,
		arg.WorkloadAction,
		arg.WorkloadActionAt,
		arg.RolledBackFrom,
		arg.Health,
		arg.Detail,
		arg.ReportedAt,
		arg.Restarts,
		arg.Removed,
		arg.RetainedPaths,
	)
	return err
}

const upsertNodeFacts = `-- name: UpsertNodeFacts :exec
INSERT INTO node_facts (node_id, facts, capabilities, collected_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (node_id) DO UPDATE SET
    facts        = excluded.facts,
    capabilities = excluded.capabilities,
    collected_at = excluded.collected_at
`

type UpsertNodeFactsParams struct {
	NodeID       int64
	Facts        string
	Capabilities string
	CollectedAt  string
}

func (q *Queries) UpsertNodeFacts(ctx context.Context, arg UpsertNodeFactsParams) error {
	_, err := q.db.ExecContext(ctx, upsertNodeFacts,
		arg.NodeID,
		arg.Facts,
		arg.Capabilities,
		arg.CollectedAt,
	)
	return err
}

const upsertNodeOrphan = `-- name: UpsertNodeOrphan :exec
INSERT INTO node_orphans (node_id, instance_key, first_seen_at, last_seen_at, paths)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (node_id, instance_key) DO UPDATE SET
    last_seen_at = excluded.last_seen_at,
    paths        = excluded.paths
`

type UpsertNodeOrphanParams struct {
	NodeID      int64
	InstanceKey string
	FirstSeenAt string
	LastSeenAt  string
	Paths       string
}

// purge_requested_at is deliberately NOT updated here: it is set by the
// operator and must survive every subsequent report. The row disappears on
// its own once the node stops reporting the orphan, which is what clears it.
func (q *Queries) UpsertNodeOrphan(ctx context.Context, arg UpsertNodeOrphanParams) error {
	_, err := q.db.ExecContext(ctx, upsertNodeOrphan,
		arg.NodeID,
		arg.InstanceKey,
		arg.FirstSeenAt,
		arg.LastSeenAt,
		arg.Paths,
	)
	return err
}
