// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	ActiveRollout(ctx context.Context, componentID int64) (Rollout, error)
	AppendAudit(ctx context.Context, arg AppendAuditParams) error
	AppendEvent(ctx context.Context, arg AppendEventParams) error
	// Turns a "node add"-only row (status='reserved', no cert ever issued) into
	// a claimed one, in place. Only matches rows still in 'reserved' status, so
	// it cannot be used to steal an identity that already has a cert.
	// Zero rows matched surfaces to Go as sql.ErrNoRows.
	ClaimReservedNode(ctx context.Context, arg ClaimReservedNodeParams) (Node, error)
	ClearDrift(ctx context.Context, roleInstanceID int64) error
	CountDependents(ctx context.Context, boundComponentID int64) (int64, error)
	CountNodeOrphans(ctx context.Context, nodeID int64) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	// -- components ----------------------------------------------------------
	CreateComponent(ctx context.Context, arg CreateComponentParams) (Component, error)
	// -- join_tokens ---------------------------------------------------------
	CreateJoinToken(ctx context.Context, arg CreateJoinTokenParams) (JoinToken, error)
	CreatePackBinding(ctx context.Context, arg CreatePackBindingParams) (PackBinding, error)
	CreateRoleInstance(ctx context.Context, arg CreateRoleInstanceParams) (RoleInstance, error)
	// -- rollouts ------------------------------------------------------------
	CreateRollout(ctx context.Context, arg CreateRolloutParams) (Rollout, error)
	// -- rollout_batches ------------------------------------------------------
	CreateRolloutBatch(ctx context.Context, arg CreateRolloutBatchParams) (RolloutBatch, error)
	// -- sessions -----------------------------------------------------------
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	// Queries for expected state (the part that MUST be backed up).
	// See docs/design/07-persistence.md section 1.7.
	//
	// IMPORTANT: comments in this file must be ASCII only.
	// sqlc strips comments by byte offset; multi-byte characters shift those
	// offsets and silently corrupt the generated SQL (it produced identifiers
	// like "INSEid" and "GetC" before we found this). The Chinese rationale for
	// each query lives in the Go repository layer instead.
	// A unit test enforces the ASCII constraint.
	// -- sites ---------------------------------------------------------------
	CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error)
	CreateSuppression(ctx context.Context, arg CreateSuppressionParams) (Suppression, error)
	// -- users --------------------------------------------------------------
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteComponent(ctx context.Context, id int64) error
	DeleteConfigGroup(ctx context.Context, arg DeleteConfigGroupParams) error
	DeleteExpiredSessions(ctx context.Context, expiresAt string) error
	DeleteNode(ctx context.Context, id int64) error
	// Rows not touched by this round are stale. Compare with <> rather than <:
	// < assumes the clock strictly advances, and it does not have to. If the
	// clock steps backwards (NTP), rows stamped in the future are never < the
	// current stamp and would survive forever. <> means "not written by this
	// round", which is the actual intent and holds whatever the clock does.
	DeleteNodeOrphansNotIn(ctx context.Context, arg DeleteNodeOrphansNotInParams) error
	DeleteRoleInstance(ctx context.Context, id int64) error
	DeleteSession(ctx context.Context, tokenHash string) error
	DeleteSessionsOfUser(ctx context.Context, userName string) error
	DeleteUser(ctx context.Context, name string) error
	GetComponent(ctx context.Context, id int64) (Component, error)
	GetComponentByName(ctx context.Context, arg GetComponentByNameParams) (Component, error)
	GetConfigGroup(ctx context.Context, arg GetConfigGroupParams) (ConfigGroup, error)
	GetInstanceStatus(ctx context.Context, roleInstanceID int64) (InstanceStatus, error)
	GetJoinTokenByHash(ctx context.Context, tokenHash string) (JoinToken, error)
	GetNode(ctx context.Context, id int64) (Node, error)
	GetNodeByName(ctx context.Context, arg GetNodeByNameParams) (Node, error)
	GetNodeFacts(ctx context.Context, nodeID int64) (NodeFact, error)
	// -- pack_bindings -------------------------------------------------------
	GetPackBinding(ctx context.Context, arg GetPackBindingParams) (PackBinding, error)
	GetRoleInstance(ctx context.Context, arg GetRoleInstanceParams) (RoleInstance, error)
	GetRollout(ctx context.Context, id int64) (Rollout, error)
	// -- secrets -------------------------------------------------------------
	GetSecret(ctx context.Context, arg GetSecretParams) (Secret, error)
	GetSession(ctx context.Context, tokenHash string) (Session, error)
	GetSite(ctx context.Context, id int64) (Site, error)
	GetSiteByName(ctx context.Context, name string) (Site, error)
	GetUserByName(ctx context.Context, name string) (User, error)
	// -- vault_keys ----------------------------------------------------------
	GetWrappedDEK(ctx context.Context) (VaultKey, error)
	// Plain insert, no ON CONFLICT: fails with SQLITE_CONSTRAINT_UNIQUE when
	// (site_id, name) is already taken. Used by the join claim, which must
	// reject rather than silently overwrite an existing identity.
	InsertNode(ctx context.Context, arg InsertNodeParams) (Node, error)
	ListAllNodeOrphans(ctx context.Context) ([]NodeOrphan, error)
	ListAudit(ctx context.Context, limit int64) ([]Audit, error)
	ListComponents(ctx context.Context, siteID int64) ([]Component, error)
	ListConfigGroups(ctx context.Context, componentID int64) ([]ConfigGroup, error)
	// Names the components that depend on this one, plus which require slot binds
	// them. A bare count cannot answer the only question the user actually has
	// when a removal is refused: which ones, and do I still need them.
	ListDependents(ctx context.Context, boundComponentID int64) ([]ListDependentsRow, error)
	ListDriftByComponent(ctx context.Context, componentID int64) ([]DriftReport, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error)
	ListInstanceStatusByComponent(ctx context.Context, componentID int64) ([]InstanceStatus, error)
	ListJoinTokens(ctx context.Context, siteID int64) ([]JoinToken, error)
	ListNodeOrphans(ctx context.Context, nodeID int64) ([]NodeOrphan, error)
	ListNodes(ctx context.Context, siteID int64) ([]Node, error)
	// length(...) > 0 rather than != '': sqlc 1.31 strips the quotes off a
	// string literal here too, leaving a syntax error. Same trap as the
	// UPDATE ... SET case in expected.sql.
	ListOrphanPurges(ctx context.Context, nodeID int64) ([]string, error)
	ListPackBindings(ctx context.Context, componentID int64) ([]PackBinding, error)
	// -- role_instances ------------------------------------------------------
	ListRoleInstances(ctx context.Context, componentID int64) ([]RoleInstance, error)
	ListRoleInstancesByNode(ctx context.Context, nodeID int64) ([]RoleInstance, error)
	ListRoleInstancesByRole(ctx context.Context, arg ListRoleInstancesByRoleParams) ([]RoleInstance, error)
	ListRolloutBatches(ctx context.Context, rolloutID int64) ([]RolloutBatch, error)
	ListRollouts(ctx context.Context, arg ListRolloutsParams) ([]Rollout, error)
	ListSecrets(ctx context.Context, componentID int64) ([]Secret, error)
	ListSites(ctx context.Context) ([]Site, error)
	ListSuppressionsByComponent(ctx context.Context, arg ListSuppressionsByComponentParams) ([]Suppression, error)
	ListUsers(ctx context.Context) ([]User, error)
	// Returns -1 when the role has no instances, so the first one gets 0.
	// Do NOT use count(): ordinals may have holes and count() would collide
	// with an already-used number. See ADR-0028.
	MaxOrdinal(ctx context.Context, arg MaxOrdinalParams) (interface{}, error)
	PruneSuppressions(ctx context.Context, expiresAt string) error
	// First write stores version=1; rotation bumps it. The version participates
	// in the spec digest, so rotation necessarily produces a new generation.
	// See docs/design/16-secrets.md section 5.
	PutSecret(ctx context.Context, arg PutSecretParams) (Secret, error)
	PutWrappedDEK(ctx context.Context, arg PutWrappedDEKParams) error
	ReleaseRolloutBatch(ctx context.Context, arg ReleaseRolloutBatchParams) error
	RequestOrphanPurge(ctx context.Context, arg RequestOrphanPurgeParams) (int64, error)
	RevokeJoinToken(ctx context.Context, arg RevokeJoinTokenParams) error
	SetComponentRollout(ctx context.Context, arg SetComponentRolloutParams) error
	SetComponentRunState(ctx context.Context, arg SetComponentRunStateParams) (int64, error)
	SetNodeCordoned(ctx context.Context, arg SetNodeCordonedParams) error
	SetNodeRevoked(ctx context.Context, arg SetNodeRevokedParams) error
	SetNodeStatus(ctx context.Context, arg SetNodeStatusParams) error
	SetRoleInstanceConfigGroup(ctx context.Context, arg SetRoleInstanceConfigGroupParams) error
	SetRoleInstanceFacts(ctx context.Context, arg SetRoleInstanceFactsParams) error
	SetRoleInstanceRunState(ctx context.Context, arg SetRoleInstanceRunStateParams) error
	SetRolloutBatchGate(ctx context.Context, arg SetRolloutBatchGateParams) error
	SetRolloutBatchState(ctx context.Context, arg SetRolloutBatchStateParams) error
	SetRolloutState(ctx context.Context, arg SetRolloutStateParams) error
	SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error
	// Writes the lifecycle state and the three switches in one statement; see
	// the Go wrapper for why they must not be written separately.
	//
	// The state is a bound parameter, not a literal: sqlc 1.31 STRIPS THE QUOTES
	// off a string literal on the right-hand side of an UPDATE ... SET, turning
	// SET state = removing into SET state = removing -- a column reference.
	// It exits 0 while doing this. The failure only shows up at runtime as
	// "no such column: removing".
	StartComponentRemoval(ctx context.Context, arg StartComponentRemovalParams) error
	UpdateComponent(ctx context.Context, arg UpdateComponentParams) (Component, error)
	// -- config_groups -------------------------------------------------------
	UpsertConfigGroup(ctx context.Context, arg UpsertConfigGroupParams) (ConfigGroup, error)
	UpsertDriftReport(ctx context.Context, arg UpsertDriftReportParams) error
	// Observed state: what mechlet reports back.
	//
	// ASCII ONLY. sqlc silently corrupts identifiers when a query file contains
	// non-ASCII bytes -- and it exits 0 while doing so. See store_test.go
	// (TestQueryFilesAreASCII). Chinese commentary belongs in the Go code.
	UpsertInstanceStatus(ctx context.Context, arg UpsertInstanceStatusParams) error
	// -- nodes ---------------------------------------------------------------
	UpsertNode(ctx context.Context, arg UpsertNodeParams) (Node, error)
	UpsertNodeFacts(ctx context.Context, arg UpsertNodeFactsParams) error
	// purge_requested_at is deliberately NOT updated here: it is set by the
	// operator and must survive every subsequent report. The row disappears on
	// its own once the node stops reporting the orphan, which is what clears it.
	UpsertNodeOrphan(ctx context.Context, arg UpsertNodeOrphanParams) error
	UseJoinTokenIfAvailable(ctx context.Context, arg UseJoinTokenIfAvailableParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
