// Package mecharion.agent.v1 是 mechd 与 mechlet 之间的协议。
//
// 设计见 docs/design/17-protocol.md 与 ADR-0029。
//
// **包名带大版本**：不兼容变更换包名（v2），两版可并存，因而控制面与 agent
// 可以分别升级——多节点场景下「先升哪个」必须是运维自己能决定的事。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.0
// source: mecharion/agent/v1/agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	NodeName string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	// agent_version 是 mechlet 自身的版本，仅用于展示与排障。
	AgentVersion string `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	// max_spec_schema 是它能理解的最高 ResolvedSpec 版本。
	MaxSpecSchema uint32            `protobuf:"varint,3,opt,name=max_spec_schema,json=maxSpecSchema,proto3" json:"max_spec_schema,omitempty"`
	Caps          []*Capability     `protobuf:"bytes,4,rep,name=caps,proto3" json:"caps,omitempty"`
	Address       string            `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Labels        map[string]string `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_mecharion_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterRequest) GetMaxSpecSchema() uint32 {
	if x != nil {
		return x.MaxSpecSchema
	}
	return 0
}

func (x *RegisterRequest) GetCaps() []*Capability {
	if x != nil {
		return x.Caps
	}
	return nil
}

func (x *RegisterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// spec_schema 是 mechd 决定用来下发的版本：
	//
	//	min(mechd 支持的最高版本, mechlet 上报的 max_spec_schema)
	//
	// **控制面向后兼容 agent**：mechlet 比 mechd 新是允许的（按旧结构工作），
	// 比 mechd 的支持下限旧则被拒绝并告知需要升到哪个版本。
	SpecSchema         uint32 `protobuf:"varint,1,opt,name=spec_schema,json=specSchema,proto3" json:"spec_schema,omitempty"`
	ReconcileIntervalS uint32 `protobuf:"varint,2,opt,name=reconcile_interval_s,json=reconcileIntervalS,proto3" json:"reconcile_interval_s,omitempty"`
	ReportIntervalS    uint32 `protobuf:"varint,3,opt,name=report_interval_s,json=reportIntervalS,proto3" json:"report_interval_s,omitempty"`
	// session 标识本次会话，Subscribe 与 Report 带上它。
	Session         string `protobuf:"bytes,4,opt,name=session,proto3" json:"session,omitempty"`
	HealthIntervalS uint32 `protobuf:"varint,5,opt,name=health_interval_s,json=healthIntervalS,proto3" json:"health_interval_s,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_mecharion_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSpecSchema() uint32 {
	if x != nil {
		return x.SpecSchema
	}
	return 0
}

func (x *RegisterResponse) GetReconcileIntervalS() uint32 {
	if x != nil {
		return x.ReconcileIntervalS
	}
	return 0
}

func (x *RegisterResponse) GetReportIntervalS() uint32 {
	if x != nil {
		return x.ReportIntervalS
	}
	return 0
}

func (x *RegisterResponse) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *RegisterResponse) GetHealthIntervalS() uint32 {
	if x != nil {
		return x.HealthIntervalS
	}
	return 0
}

// Capability 是节点上某项运行时的能力，如 systemd 252 / docker 24。
type Capability struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Name      string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version   string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Available bool                   `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
	// detail 承载该 runtime 特有的细节，键名由各 runtime 自定。
	Detail        map[string]string `protobuf:"bytes,4,rep,name=detail,proto3" json:"detail,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_mecharion_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Capability) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Capability) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Capability) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *Capability) GetDetail() map[string]string {
	if x != nil {
		return x.Detail
	}
	return nil
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Session       string                 `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_mecharion_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *SubscribeRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

// Assignment 是「这台机器上应该有什么」。
//
// **里面没有动词。** mechlet 收到的是期望状态而不是指令，怎么达成是它自己
// 的事——这正是它在断连时仍能工作的原因。指令式接口会让断连自治不可能。
type Assignment struct {
	state protoimpl.MessageState  `protogen:"open.v1"`
	Specs []*ResolvedSpecEnvelope `protobuf:"bytes,1,rep,name=specs,proto3" json:"specs,omitempty"`
	// full_sync 为 true 表示这是全量：未列出的实例应当移除。
	//
	// 重连、mechd 重启、期望状态变化——**一律推全量**。不做增量同步、
	// 不做确认序号、不做差异计算：下发本身幂等（digest 相同即无操作），
	// 一个内容寻址的期望状态让整类同步协议问题消失。
	FullSync bool `protobuf:"varint,2,opt,name=full_sync,json=fullSync,proto3" json:"full_sync,omitempty"`
	// revision 仅用于日志与排障，不参与任何判定。
	Revision uint64 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	// cordoned 表示这台机器**当前被暂停调和**。
	//
	// 它是**状态不是动词**（ADR-0029）：下发说的永远是「这台机器现在是
	// 什么情况」，而不是「去暂停」。因此重连时随全量一起重推，节点不需要
	// 记住任何一次性的指令。
	//
	// 语义是「别动这台机器」：运行中的进程不碰，只停止调和。那正是
	// 「我要手工调试这台机，别让 mechlet 把我的改动改回去」（10-cli §4.2）。
	Cordoned bool `protobuf:"varint,4,opt,name=cordoned,proto3" json:"cordoned,omitempty"`
	// purge_orphans 是**该被清掉的孤儿实例键**。
	//
	// 它是状态不是动词，与 cordoned 同：节点每次收到都照做一遍，删一个
	// 已经不在的目录是 no-op；断连三天回来仍然会收到它。
	//
	// **带的是实例键，不是绝对路径。** 节点删的是自己本地收据里记的那些
	// 目录。考虑这个时序：purge 下发时节点失联，其间运维用同名重新部署了
	// 组件，节点回来之后收到那条 purge——若带的是绝对路径，它会把**新数据**
	// 删掉。带实例键则不会：那时本地状态已经是一个真实实例而不是收据，
	// purge 直接空跑。
	PurgeOrphans  []string `protobuf:"bytes,5,rep,name=purge_orphans,json=purgeOrphans,proto3" json:"purge_orphans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assignment) Reset() {
	*x = Assignment{}
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assignment) ProtoMessage() {}

func (x *Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assignment.ProtoReflect.Descriptor instead.
func (*Assignment) Descriptor() ([]byte, []int) {
	return file_mecharion_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Assignment) GetSpecs() []*ResolvedSpecEnvelope {
	if x != nil {
		return x.Specs
	}
	return nil
}

func (x *Assignment) GetFullSync() bool {
	if x != nil {
		return x.FullSync
	}
	return false
}

func (x *Assignment) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Assignment) GetCordoned() bool {
	if x != nil {
		return x.Cordoned
	}
	return false
}

func (x *Assignment) GetPurgeOrphans() []string {
	if x != nil {
		return x.PurgeOrphans
	}
	return nil
}

type ResolvedSpecEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// spec_json 是 ResolvedSpec，其中敏感值已换成 @@m7n:secret:<id>@@。
	SpecJson []byte `protobuf:"bytes,1,opt,name=spec_json,json=specJson,proto3" json:"spec_json,omitempty"`
	// secrets 是 id → 明文，**唯一承载明文的地方**。
	//
	// mechlet 只在内存持有：不写 spec 归档、不写日志、不参与 digest。
	// 重启后重新 Register + Subscribe 拿一次——与「重连即全量重推」
	// 是同一条路径，不额外设计。
	Secrets       map[string][]byte `protobuf:"bytes,2,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvedSpecEnvelope) Reset() {
	*x = ResolvedSpecEnvelope{}
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedSpecEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedSpecEnvelope) ProtoMessage() {}

func (x *ResolvedSpecEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedSpecEnvelope.ProtoReflect.Descriptor instead.
func (*ResolvedSpecEnvelope) Descriptor() ([]byte, []int) {
	return file_mecharion_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ResolvedSpecEnvelope) GetSpecJson() []byte {
	if x != nil {
		return x.SpecJson
	}
	return nil
}

func (x *ResolvedSpecEnvelope) GetSecrets() map[string][]byte {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type TasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Session       string                 `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TasksRequest) Reset() {
	*x = TasksRequest{}
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TasksRequest) ProtoMessage() {}

func (x *TasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TasksRequest.ProtoReflect.Descriptor instead.
func (*TasksRequest) Descriptor() ([]byte, []int) {
	return file_mecharion_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *TasksRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *TasksRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

// Task 是一条一次性命令。
//
// **它不落库、不重试、不排队**（ADR-0038）：离线就是离线，如实报告。
// 一个「等它上线再执行」的队列会让人以为命令一定会生效，而那是期望状态
// 的语义——真需要那种语义的东西，本来就该做成期望状态。
type Task struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id 用于把结果对回来。
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// kind 是命令类型。**显式枚举，加一种要过一次评审**：这是一条真正的
	// 命令通道，「顺手加个 task 类型」比往 Assignment 里加字段容易得多。
	//
	//	restart  重启一个角色实例的工作负载
	//
	// 后续的 exec / logs 在这里加。
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// component / role 定位到一个角色实例。
	Component string `protobuf:"bytes,3,opt,name=component,proto3" json:"component,omitempty"`
	Role      string `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	// deadline 是这条命令的最晚完成时刻（RFC3339）。
	//
	// **节点侧也要看它**：一条已经超时的命令，中心早已把它报成失败并
	// 返回给用户了，此时再去动机器只会制造一次没人预期的重启。
	Deadline      string `protobuf:"bytes,5,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_mecharion_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Task) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *Task) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Task) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

type TaskResultRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	NodeName string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Session  string                 `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	TaskId   string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// ok 为 false 时 message 说明原因。
	Ok      bool   `protobuf:"varint,4,opt,name=ok,proto3" json:"ok,omitempty"`
	Message string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	// duration_ms 让「慢」与「失败」分得开。
	DurationMs    int64 `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResultRequest) Reset() {
	*x = TaskResultRequest{}
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResultRequest) ProtoMessage() {}

func (x *TaskResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResultRequest.ProtoReflect.Descriptor instead.
func (*TaskResultRequest) Descriptor() ([]byte, []int) {
	return file_mecharion_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *TaskResultRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *TaskResultRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *TaskResultRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResultRequest) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TaskResultRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskResultRequest) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type TaskResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResultResponse) Reset() {
	*x = TaskResultResponse{}
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResultResponse) ProtoMessage() {}

func (x *TaskResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResultResponse.ProtoReflect.Descriptor instead.
func (*TaskResultResponse) Descriptor() ([]byte, []int) {
	return file_mecharion_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

type ReportRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	NodeName  string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Session   string                 `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	Instances []*InstanceStatus      `protobuf:"bytes,3,rep,name=instances,proto3" json:"instances,omitempty"`
	// facts 周期性刷新。它是**观测值**，不自动改变已固化的配置取值。
	Facts *NodeFacts `protobuf:"bytes,4,opt,name=facts,proto3" json:"facts,omitempty"`
	// orphans 是**机器上还在、但下发里没有**的实例键。
	//
	// mechlet 只报不删：卸载不可逆，而「mechd 少发了一条」与「用户真的
	// 删了这个组件」在节点侧分辨不了。
	Orphans []string `protobuf:"bytes,5,rep,name=orphans,proto3" json:"orphans,omitempty"`
	// orphan_records 是同一批孤儿，外加**它们在盘上留下了什么**。
	//
	// 只报一个键回答不了唯一要紧的问题：那台机器上到底还剩什么、在哪儿。
	// 10-cli §4.3 明写「保留而不提供发现机制等于把问题推给未来」。
	//
	// 与 orphans 并存而不是取代它：字段类型改不了（线上格式），而这两个
	// 列表**由同一段代码同时产出**，不会分叉。
	OrphanRecords []*OrphanRecord `protobuf:"bytes,6,rep,name=orphan_records,json=orphanRecords,proto3" json:"orphan_records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRequest) Reset() {
	*x = ReportRequest{}
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRequest) ProtoMessage() {}

func (x *ReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRequest.ProtoReflect.Descriptor instead.
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return file_mecharion_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ReportRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *ReportRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *ReportRequest) GetInstances() []*InstanceStatus {
	if x != nil {
		return x.Instances
	}
	return nil
}

func (x *ReportRequest) GetFacts() *NodeFacts {
	if x != nil {
		return x.Facts
	}
	return nil
}

func (x *ReportRequest) GetOrphans() []string {
	if x != nil {
		return x.Orphans
	}
	return nil
}

func (x *ReportRequest) GetOrphanRecords() []*OrphanRecord {
	if x != nil {
		return x.OrphanRecords
	}
	return nil
}

type ReportResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// resync 让 mechd 要求 mechlet 重新 Subscribe，用于会话失效等情形。
	Resync        bool `protobuf:"varint,1,opt,name=resync,proto3" json:"resync,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_mecharion_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ReportResponse) GetResync() bool {
	if x != nil {
		return x.Resync
	}
	return false
}

type InstanceStatus struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Component string                 `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"`
	Role      string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	// digest 是当前生效的 generation 的 digest。
	//
	// **它是收敛判据**：Rollout 靠「上报的 digest == 期望的 digest 且健康」
	// 判定一批完成，而不是靠 mechlet 说「我成功了」。前者是状态，后者是事件——
	// 状态可以重复确认，事件丢一次就永远丢了。
	Digest     string `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	Generation int32  `protobuf:"varint,4,opt,name=generation,proto3" json:"generation,omitempty"`
	// result 取 ok | changed | drift | failed。
	Result     string             `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	Workload   *WorkloadStatus    `protobuf:"bytes,6,opt,name=workload,proto3" json:"workload,omitempty"`
	Health     *HealthStatus      `protobuf:"bytes,7,opt,name=health,proto3" json:"health,omitempty"`
	Resources  []*ResourceStatus  `protobuf:"bytes,8,rep,name=resources,proto3" json:"resources,omitempty"`
	Suppressed []*SuppressedDrift `protobuf:"bytes,9,rep,name=suppressed,proto3" json:"suppressed,omitempty"`
	Message    string             `protobuf:"bytes,10,opt,name=message,proto3" json:"message,omitempty"`
	// workload_action 是调和器本轮**对工作负载做了什么**：restored | stopped。
	//
	// 没有它，一次「服务被人停了、调和把它拉起来」在中心完全不可见——
	// 没有资源被 Apply、没有切软链，一个每分钟崩一次又被拉起的服务
	// 看起来完全健康。
	WorkloadAction string `protobuf:"bytes,11,opt,name=workload_action,json=workloadAction,proto3" json:"workload_action,omitempty"`
	// workload_action_at 是它发生的时刻（RFC3339）。
	//
	// **带上时间才让它成为状态**：不带的话它只是「上一轮做了什么」，
	// 而上报是周期快照——调和比上报密时那一轮会被覆盖掉，事件就丢了。
	WorkloadActionAt string `protobuf:"bytes,12,opt,name=workload_action_at,json=workloadActionAt,proto3" json:"workload_action_at,omitempty"`
	// rolled_back_from 是被节点自动回滚掉的那个 digest。
	//
	// **只有节点知道它做了什么**：mechd 看到的只是「上报的 digest 不是期望的
	// 那个」，而那与「还没来得及升级」长得一样。Rollout 要靠它区分
	// 「失败并已回滚」与「正在推进」。
	RolledBackFrom string `protobuf:"bytes,13,opt,name=rolled_back_from,json=rolledBackFrom,proto3" json:"rolled_back_from,omitempty"`
	// removed 表示这个实例**已经按 runState: removed 拆干净了**。
	//
	// 它是 mechd 把 Component 从 removing 推进到「记录删除」的唯一依据。
	// digest 在这里帮不上忙：RunState 不参与 digest，因此一个拆完的实例
	// 与一个装着的实例上报的 digest 一模一样——分辨不出来。
	//
	// **是状态不是事件**：只要那份规格还说 removed，节点每一轮调和都会
	// 重新确认一次并再报一次 true。丢掉一次上报没有后果，下一轮照旧。
	Removed bool `protobuf:"varint,14,opt,name=removed,proto3" json:"removed,omitempty"`
	// retained_paths 是卸载时**故意留下**的目录（数据默认保留）。
	//
	// 跟着「拆完了」一起报，是因为这两件事在同一时刻才都成立：再晚一步
	// 记录就被删了，那些目录会变成没人说得清来历的孤儿。
	RetainedPaths []string `protobuf:"bytes,15,rep,name=retained_paths,json=retainedPaths,proto3" json:"retained_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceStatus) Reset() {
	*x = InstanceStatus{}
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceStatus) ProtoMessage() {}

func (x *InstanceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceStatus.ProtoReflect.Descriptor instead.
func (*InstanceStatus) Descriptor() ([]byte, []int) {
	return file_mecharion_agent_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *InstanceStatus) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *InstanceStatus) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *InstanceStatus) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *InstanceStatus) GetGeneration() int32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *InstanceStatus) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *InstanceStatus) GetWorkload() *WorkloadStatus {
	if x != nil {
		return x.Workload
	}
	return nil
}

func (x *InstanceStatus) GetHealth() *HealthStatus {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *InstanceStatus) GetResources() []*ResourceStatus {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *InstanceStatus) GetSuppressed() []*SuppressedDrift {
	if x != nil {
		return x.Suppressed
	}
	return nil
}

func (x *InstanceStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InstanceStatus) GetWorkloadAction() string {
	if x != nil {
		return x.WorkloadAction
	}
	return ""
}

func (x *InstanceStatus) GetWorkloadActionAt() string {
	if x != nil {
		return x.WorkloadActionAt
	}
	return ""
}

func (x *InstanceStatus) GetRolledBackFrom() string {
	if x != nil {
		return x.RolledBackFrom
	}
	return ""
}

func (x *InstanceStatus) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

func (x *InstanceStatus) GetRetainedPaths() []string {
	if x != nil {
		return x.RetainedPaths
	}
	return nil
}

// OrphanRecord 是一个孤儿实例，以及它在盘上留下的东西。
type OrphanRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key 形如 "pg-main__primary"。
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// retained_paths 是卸载时故意留下的目录（数据默认保留）。
	//
	// 空表示这个孤儿不是 remove 留下的，而是「下发里没有它了」——
	// 那时机器上留着的是一整个还装着的实例，不只是几个目录。
	RetainedPaths []string `protobuf:"bytes,2,rep,name=retained_paths,json=retainedPaths,proto3" json:"retained_paths,omitempty"`
	// pack / version 说明这堆东西是谁、哪一版留下的。
	//
	// **决定「能不能删」时唯一要紧的信息。** 一个只有路径的孤儿回答不了它。
	Pack    string `protobuf:"bytes,3,opt,name=pack,proto3" json:"pack,omitempty"`
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// removed_at 是卸载完成的时刻（RFC3339），非 remove 留下的孤儿为空。
	RemovedAt     string `protobuf:"bytes,5,opt,name=removed_at,json=removedAt,proto3" json:"removed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrphanRecord) Reset() {
	*x = OrphanRecord{}
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrphanRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrphanRecord) ProtoMessage() {}

func (x *OrphanRecord) ProtoReflect() protoreflect.Message {
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrphanRecord.ProtoReflect.Descriptor instead.
func (*OrphanRecord) Descriptor() ([]byte, []int) {
	return file_mecharion_agent_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *OrphanRecord) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OrphanRecord) GetRetainedPaths() []string {
	if x != nil {
		return x.RetainedPaths
	}
	return nil
}

func (x *OrphanRecord) GetPack() string {
	if x != nil {
		return x.Pack
	}
	return ""
}

func (x *OrphanRecord) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *OrphanRecord) GetRemovedAt() string {
	if x != nil {
		return x.RemovedAt
	}
	return ""
}

type WorkloadStatus struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Runtime string                 `protobuf:"bytes,1,opt,name=runtime,proto3" json:"runtime,omitempty"`
	// state 取 running | stopped | failed | unknown。
	State         string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Pid           int64  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	Since         string `protobuf:"bytes,4,opt,name=since,proto3" json:"since,omitempty"`
	Restarts      int32  `protobuf:"varint,5,opt,name=restarts,proto3" json:"restarts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadStatus) Reset() {
	*x = WorkloadStatus{}
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadStatus) ProtoMessage() {}

func (x *WorkloadStatus) ProtoReflect() protoreflect.Message {
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadStatus.ProtoReflect.Descriptor instead.
func (*WorkloadStatus) Descriptor() ([]byte, []int) {
	return file_mecharion_agent_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *WorkloadStatus) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *WorkloadStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *WorkloadStatus) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *WorkloadStatus) GetSince() string {
	if x != nil {
		return x.Since
	}
	return ""
}

func (x *WorkloadStatus) GetRestarts() int32 {
	if x != nil {
		return x.Restarts
	}
	return 0
}

type HealthStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// state 取 healthy | unhealthy | unknown。
	State               string `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	ConsecutiveFailures int32  `protobuf:"varint,2,opt,name=consecutive_failures,json=consecutiveFailures,proto3" json:"consecutive_failures,omitempty"`
	LastError           string `protobuf:"bytes,3,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	CheckedAt           string `protobuf:"bytes,4,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HealthStatus) Reset() {
	*x = HealthStatus{}
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatus) ProtoMessage() {}

func (x *HealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatus.ProtoReflect.Descriptor instead.
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return file_mecharion_agent_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *HealthStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *HealthStatus) GetConsecutiveFailures() int32 {
	if x != nil {
		return x.ConsecutiveFailures
	}
	return 0
}

func (x *HealthStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *HealthStatus) GetCheckedAt() string {
	if x != nil {
		return x.CheckedAt
	}
	return ""
}

type ResourceStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type  string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// state 取 ok | drift | failed。
	State         string `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Detail        string `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceStatus) Reset() {
	*x = ResourceStatus{}
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceStatus) ProtoMessage() {}

func (x *ResourceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceStatus.ProtoReflect.Descriptor instead.
func (*ResourceStatus) Descriptor() ([]byte, []int) {
	return file_mecharion_agent_v1_agent_proto_rawDescGZIP(), []int{16}
}

func (x *ResourceStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResourceStatus) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ResourceStatus) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type SuppressedDrift struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Until         string                 `protobuf:"bytes,3,opt,name=until,proto3" json:"until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuppressedDrift) Reset() {
	*x = SuppressedDrift{}
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuppressedDrift) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuppressedDrift) ProtoMessage() {}

func (x *SuppressedDrift) ProtoReflect() protoreflect.Message {
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuppressedDrift.ProtoReflect.Descriptor instead.
func (*SuppressedDrift) Descriptor() ([]byte, []int) {
	return file_mecharion_agent_v1_agent_proto_rawDescGZIP(), []int{17}
}

func (x *SuppressedDrift) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *SuppressedDrift) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SuppressedDrift) GetUntil() string {
	if x != nil {
		return x.Until
	}
	return ""
}

type NodeFacts struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// facts_json 是完整事实集，结构见 spec §9.4.2。
	//
	// 用 JSON 而非展开成 proto 字段：事实集会随发行版与硬件演进不断加字段，
	// 每次都要改协议、两端同时升级，代价与收益完全不成比例。它本就是
	// 给模板读的自由结构。
	FactsJson     []byte `protobuf:"bytes,1,opt,name=facts_json,json=factsJson,proto3" json:"facts_json,omitempty"`
	CollectedAt   string `protobuf:"bytes,2,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeFacts) Reset() {
	*x = NodeFacts{}
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeFacts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeFacts) ProtoMessage() {}

func (x *NodeFacts) ProtoReflect() protoreflect.Message {
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeFacts.ProtoReflect.Descriptor instead.
func (*NodeFacts) Descriptor() ([]byte, []int) {
	return file_mecharion_agent_v1_agent_proto_rawDescGZIP(), []int{18}
}

func (x *NodeFacts) GetFactsJson() []byte {
	if x != nil {
		return x.FactsJson
	}
	return nil
}

func (x *NodeFacts) GetCollectedAt() string {
	if x != nil {
		return x.CollectedAt
	}
	return ""
}

type PushEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Session       string                 `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	Events        []*Event               `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushEventsRequest) Reset() {
	*x = PushEventsRequest{}
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushEventsRequest) ProtoMessage() {}

func (x *PushEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushEventsRequest.ProtoReflect.Descriptor instead.
func (*PushEventsRequest) Descriptor() ([]byte, []int) {
	return file_mecharion_agent_v1_agent_proto_rawDescGZIP(), []int{19}
}

func (x *PushEventsRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *PushEventsRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *PushEventsRequest) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type PushEventsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// accepted 是已接收的事件数，mechlet 据此裁掉本地缓冲。
	Accepted      uint32 `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushEventsResponse) Reset() {
	*x = PushEventsResponse{}
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushEventsResponse) ProtoMessage() {}

func (x *PushEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushEventsResponse.ProtoReflect.Descriptor instead.
func (*PushEventsResponse) Descriptor() ([]byte, []int) {
	return file_mecharion_agent_v1_agent_proto_rawDescGZIP(), []int{20}
}

func (x *PushEventsResponse) GetAccepted() uint32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	At    string                 `protobuf:"bytes,1,opt,name=at,proto3" json:"at,omitempty"`
	// level 取 info | warn | error。
	Level         string `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Component     string `protobuf:"bytes,3,opt,name=component,proto3" json:"component,omitempty"`
	Role          string `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Kind          string `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	Message       string `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_mecharion_agent_v1_agent_proto_rawDescGZIP(), []int{21}
}

func (x *Event) GetAt() string {
	if x != nil {
		return x.At
	}
	return ""
}

func (x *Event) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Event) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *Event) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Event) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Event) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FetchBlobRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Sha256 string                 `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"`
	// offset 支持断点续传：内容寻址让这件事天然成立。
	Offset        int64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchBlobRequest) Reset() {
	*x = FetchBlobRequest{}
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchBlobRequest) ProtoMessage() {}

func (x *FetchBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchBlobRequest.ProtoReflect.Descriptor instead.
func (*FetchBlobRequest) Descriptor() ([]byte, []int) {
	return file_mecharion_agent_v1_agent_proto_rawDescGZIP(), []int{22}
}

func (x *FetchBlobRequest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *FetchBlobRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type BlobChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Data  []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// total_size 只在第一块上有意义，供接收方预分配与显示进度。
	TotalSize     int64 `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobChunk) Reset() {
	*x = BlobChunk{}
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobChunk) ProtoMessage() {}

func (x *BlobChunk) ProtoReflect() protoreflect.Message {
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobChunk.ProtoReflect.Descriptor instead.
func (*BlobChunk) Descriptor() ([]byte, []int) {
	return file_mecharion_agent_v1_agent_proto_rawDescGZIP(), []int{23}
}

func (x *BlobChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BlobChunk) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

// RenewCertRequest 是一次证书续期。
type RenewCertRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	NodeName string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	// csr_pem 是节点本机新生成的证书请求。**私钥不过网**，与 join 一致。
	CsrPem        string `protobuf:"bytes,2,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewCertRequest) Reset() {
	*x = RenewCertRequest{}
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewCertRequest) ProtoMessage() {}

func (x *RenewCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewCertRequest.ProtoReflect.Descriptor instead.
func (*RenewCertRequest) Descriptor() ([]byte, []int) {
	return file_mecharion_agent_v1_agent_proto_rawDescGZIP(), []int{24}
}

func (x *RenewCertRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *RenewCertRequest) GetCsrPem() string {
	if x != nil {
		return x.CsrPem
	}
	return ""
}

type RenewCertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertPem       string                 `protobuf:"bytes,1,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	CaPem         string                 `protobuf:"bytes,2,opt,name=ca_pem,json=caPem,proto3" json:"ca_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewCertResponse) Reset() {
	*x = RenewCertResponse{}
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewCertResponse) ProtoMessage() {}

func (x *RenewCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mecharion_agent_v1_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewCertResponse.ProtoReflect.Descriptor instead.
func (*RenewCertResponse) Descriptor() ([]byte, []int) {
	return file_mecharion_agent_v1_agent_proto_rawDescGZIP(), []int{25}
}

func (x *RenewCertResponse) GetCertPem() string {
	if x != nil {
		return x.CertPem
	}
	return ""
}

func (x *RenewCertResponse) GetCaPem() string {
	if x != nil {
		return x.CaPem
	}
	return ""
}

var File_mecharion_agent_v1_agent_proto protoreflect.FileDescriptor

const file_mecharion_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1emecharion/agent/v1/agent.proto\x12\x12mecharion.agent.v1\"\xcd\x02\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\x12&\n" +
	"\x0fmax_spec_schema\x18\x03 \x01(\rR\rmaxSpecSchema\x122\n" +
	"\x04caps\x18\x04 \x03(\v2\x1e.mecharion.agent.v1.CapabilityR\x04caps\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12G\n" +
	"\x06labels\x18\x06 \x03(\v2/.mecharion.agent.v1.RegisterRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd7\x01\n" +
	"\x10RegisterResponse\x12\x1f\n" +
	"\vspec_schema\x18\x01 \x01(\rR\n" +
	"specSchema\x120\n" +
	"\x14reconcile_interval_s\x18\x02 \x01(\rR\x12reconcileIntervalS\x12*\n" +
	"\x11report_interval_s\x18\x03 \x01(\rR\x0freportIntervalS\x12\x18\n" +
	"\asession\x18\x04 \x01(\tR\asession\x12*\n" +
	"\x11health_interval_s\x18\x05 \x01(\rR\x0fhealthIntervalS\"\xd7\x01\n" +
	"\n" +
	"Capability\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1c\n" +
	"\tavailable\x18\x03 \x01(\bR\tavailable\x12B\n" +
	"\x06detail\x18\x04 \x03(\v2*.mecharion.agent.v1.Capability.DetailEntryR\x06detail\x1a9\n" +
	"\vDetailEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"I\n" +
	"\x10SubscribeRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x18\n" +
	"\asession\x18\x02 \x01(\tR\asession\"\xc6\x01\n" +
	"\n" +
	"Assignment\x12>\n" +
	"\x05specs\x18\x01 \x03(\v2(.mecharion.agent.v1.ResolvedSpecEnvelopeR\x05specs\x12\x1b\n" +
	"\tfull_sync\x18\x02 \x01(\bR\bfullSync\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x04R\brevision\x12\x1a\n" +
	"\bcordoned\x18\x04 \x01(\bR\bcordoned\x12#\n" +
	"\rpurge_orphans\x18\x05 \x03(\tR\fpurgeOrphans\"\xc0\x01\n" +
	"\x14ResolvedSpecEnvelope\x12\x1b\n" +
	"\tspec_json\x18\x01 \x01(\fR\bspecJson\x12O\n" +
	"\asecrets\x18\x02 \x03(\v25.mecharion.agent.v1.ResolvedSpecEnvelope.SecretsEntryR\asecrets\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"E\n" +
	"\fTasksRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x18\n" +
	"\asession\x18\x02 \x01(\tR\asession\"x\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1c\n" +
	"\tcomponent\x18\x03 \x01(\tR\tcomponent\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x1a\n" +
	"\bdeadline\x18\x05 \x01(\tR\bdeadline\"\xae\x01\n" +
	"\x11TaskResultRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x18\n" +
	"\asession\x18\x02 \x01(\tR\asession\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12\x0e\n" +
	"\x02ok\x18\x04 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs\"\x14\n" +
	"\x12TaskResultResponse\"\xa0\x02\n" +
	"\rReportRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x18\n" +
	"\asession\x18\x02 \x01(\tR\asession\x12@\n" +
	"\tinstances\x18\x03 \x03(\v2\".mecharion.agent.v1.InstanceStatusR\tinstances\x123\n" +
	"\x05facts\x18\x04 \x01(\v2\x1d.mecharion.agent.v1.NodeFactsR\x05facts\x12\x18\n" +
	"\aorphans\x18\x05 \x03(\tR\aorphans\x12G\n" +
	"\x0eorphan_records\x18\x06 \x03(\v2 .mecharion.agent.v1.OrphanRecordR\rorphanRecords\"(\n" +
	"\x0eReportResponse\x12\x16\n" +
	"\x06resync\x18\x01 \x01(\bR\x06resync\"\xef\x04\n" +
	"\x0eInstanceStatus\x12\x1c\n" +
	"\tcomponent\x18\x01 \x01(\tR\tcomponent\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\tR\x06digest\x12\x1e\n" +
	"\n" +
	"generation\x18\x04 \x01(\x05R\n" +
	"generation\x12\x16\n" +
	"\x06result\x18\x05 \x01(\tR\x06result\x12>\n" +
	"\bworkload\x18\x06 \x01(\v2\".mecharion.agent.v1.WorkloadStatusR\bworkload\x128\n" +
	"\x06health\x18\a \x01(\v2 .mecharion.agent.v1.HealthStatusR\x06health\x12@\n" +
	"\tresources\x18\b \x03(\v2\".mecharion.agent.v1.ResourceStatusR\tresources\x12C\n" +
	"\n" +
	"suppressed\x18\t \x03(\v2#.mecharion.agent.v1.SuppressedDriftR\n" +
	"suppressed\x12\x18\n" +
	"\amessage\x18\n" +
	" \x01(\tR\amessage\x12'\n" +
	"\x0fworkload_action\x18\v \x01(\tR\x0eworkloadAction\x12,\n" +
	"\x12workload_action_at\x18\f \x01(\tR\x10workloadActionAt\x12(\n" +
	"\x10rolled_back_from\x18\r \x01(\tR\x0erolledBackFrom\x12\x18\n" +
	"\aremoved\x18\x0e \x01(\bR\aremoved\x12%\n" +
	"\x0eretained_paths\x18\x0f \x03(\tR\rretainedPaths\"\x94\x01\n" +
	"\fOrphanRecord\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x0eretained_paths\x18\x02 \x03(\tR\rretainedPaths\x12\x12\n" +
	"\x04pack\x18\x03 \x01(\tR\x04pack\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"removed_at\x18\x05 \x01(\tR\tremovedAt\"\x84\x01\n" +
	"\x0eWorkloadStatus\x12\x18\n" +
	"\aruntime\x18\x01 \x01(\tR\aruntime\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x03R\x03pid\x12\x14\n" +
	"\x05since\x18\x04 \x01(\tR\x05since\x12\x1a\n" +
	"\brestarts\x18\x05 \x01(\x05R\brestarts\"\x95\x01\n" +
	"\fHealthStatus\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x121\n" +
	"\x14consecutive_failures\x18\x02 \x01(\x05R\x13consecutiveFailures\x12\x1d\n" +
	"\n" +
	"last_error\x18\x03 \x01(\tR\tlastError\x12\x1d\n" +
	"\n" +
	"checked_at\x18\x04 \x01(\tR\tcheckedAt\"b\n" +
	"\x0eResourceStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\"`\n" +
	"\x0fSuppressedDrift\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x14\n" +
	"\x05until\x18\x03 \x01(\tR\x05until\"M\n" +
	"\tNodeFacts\x12\x1d\n" +
	"\n" +
	"facts_json\x18\x01 \x01(\fR\tfactsJson\x12!\n" +
	"\fcollected_at\x18\x02 \x01(\tR\vcollectedAt\"}\n" +
	"\x11PushEventsRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x18\n" +
	"\asession\x18\x02 \x01(\tR\asession\x121\n" +
	"\x06events\x18\x03 \x03(\v2\x19.mecharion.agent.v1.EventR\x06events\"0\n" +
	"\x12PushEventsResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\rR\baccepted\"\x8d\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02at\x18\x01 \x01(\tR\x02at\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x1c\n" +
	"\tcomponent\x18\x03 \x01(\tR\tcomponent\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"B\n" +
	"\x10FetchBlobRequest\x12\x16\n" +
	"\x06sha256\x18\x01 \x01(\tR\x06sha256\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\">\n" +
	"\tBlobChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x03R\ttotalSize\"H\n" +
	"\x10RenewCertRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x17\n" +
	"\acsr_pem\x18\x02 \x01(\tR\x06csrPem\"E\n" +
	"\x11RenewCertResponse\x12\x19\n" +
	"\bcert_pem\x18\x01 \x01(\tR\acertPem\x12\x15\n" +
	"\x06ca_pem\x18\x02 \x01(\tR\x05caPem2\xb9\x05\n" +
	"\x05Agent\x12U\n" +
	"\bRegister\x12#.mecharion.agent.v1.RegisterRequest\x1a$.mecharion.agent.v1.RegisterResponse\x12S\n" +
	"\tSubscribe\x12$.mecharion.agent.v1.SubscribeRequest\x1a\x1e.mecharion.agent.v1.Assignment0\x01\x12O\n" +
	"\x06Report\x12!.mecharion.agent.v1.ReportRequest\x1a\".mecharion.agent.v1.ReportResponse\x12[\n" +
	"\n" +
	"PushEvents\x12%.mecharion.agent.v1.PushEventsRequest\x1a&.mecharion.agent.v1.PushEventsResponse\x12R\n" +
	"\tFetchBlob\x12$.mecharion.agent.v1.FetchBlobRequest\x1a\x1d.mecharion.agent.v1.BlobChunk0\x01\x12X\n" +
	"\tRenewCert\x12$.mecharion.agent.v1.RenewCertRequest\x1a%.mecharion.agent.v1.RenewCertResponse\x12E\n" +
	"\x05Tasks\x12 .mecharion.agent.v1.TasksRequest\x1a\x18.mecharion.agent.v1.Task0\x01\x12a\n" +
	"\x10ReportTaskResult\x12%.mecharion.agent.v1.TaskResultRequest\x1a&.mecharion.agent.v1.TaskResultResponseBBZ@github.com/mecharion/mecharion/internal/protocol/agentpb;agentpbb\x06proto3"

var (
	file_mecharion_agent_v1_agent_proto_rawDescOnce sync.Once
	file_mecharion_agent_v1_agent_proto_rawDescData []byte
)

func file_mecharion_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_mecharion_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_mecharion_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mecharion_agent_v1_agent_proto_rawDesc), len(file_mecharion_agent_v1_agent_proto_rawDesc)))
	})
	return file_mecharion_agent_v1_agent_proto_rawDescData
}

var file_mecharion_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_mecharion_agent_v1_agent_proto_goTypes = []any{
	(*RegisterRequest)(nil),      // 0: mecharion.agent.v1.RegisterRequest
	(*RegisterResponse)(nil),     // 1: mecharion.agent.v1.RegisterResponse
	(*Capability)(nil),           // 2: mecharion.agent.v1.Capability
	(*SubscribeRequest)(nil),     // 3: mecharion.agent.v1.SubscribeRequest
	(*Assignment)(nil),           // 4: mecharion.agent.v1.Assignment
	(*ResolvedSpecEnvelope)(nil), // 5: mecharion.agent.v1.ResolvedSpecEnvelope
	(*TasksRequest)(nil),         // 6: mecharion.agent.v1.TasksRequest
	(*Task)(nil),                 // 7: mecharion.agent.v1.Task
	(*TaskResultRequest)(nil),    // 8: mecharion.agent.v1.TaskResultRequest
	(*TaskResultResponse)(nil),   // 9: mecharion.agent.v1.TaskResultResponse
	(*ReportRequest)(nil),        // 10: mecharion.agent.v1.ReportRequest
	(*ReportResponse)(nil),       // 11: mecharion.agent.v1.ReportResponse
	(*InstanceStatus)(nil),       // 12: mecharion.agent.v1.InstanceStatus
	(*OrphanRecord)(nil),         // 13: mecharion.agent.v1.OrphanRecord
	(*WorkloadStatus)(nil),       // 14: mecharion.agent.v1.WorkloadStatus
	(*HealthStatus)(nil),         // 15: mecharion.agent.v1.HealthStatus
	(*ResourceStatus)(nil),       // 16: mecharion.agent.v1.ResourceStatus
	(*SuppressedDrift)(nil),      // 17: mecharion.agent.v1.SuppressedDrift
	(*NodeFacts)(nil),            // 18: mecharion.agent.v1.NodeFacts
	(*PushEventsRequest)(nil),    // 19: mecharion.agent.v1.PushEventsRequest
	(*PushEventsResponse)(nil),   // 20: mecharion.agent.v1.PushEventsResponse
	(*Event)(nil),                // 21: mecharion.agent.v1.Event
	(*FetchBlobRequest)(nil),     // 22: mecharion.agent.v1.FetchBlobRequest
	(*BlobChunk)(nil),            // 23: mecharion.agent.v1.BlobChunk
	(*RenewCertRequest)(nil),     // 24: mecharion.agent.v1.RenewCertRequest
	(*RenewCertResponse)(nil),    // 25: mecharion.agent.v1.RenewCertResponse
	nil,                          // 26: mecharion.agent.v1.RegisterRequest.LabelsEntry
	nil,                          // 27: mecharion.agent.v1.Capability.DetailEntry
	nil,                          // 28: mecharion.agent.v1.ResolvedSpecEnvelope.SecretsEntry
}
var file_mecharion_agent_v1_agent_proto_depIdxs = []int32{
	2,  // 0: mecharion.agent.v1.RegisterRequest.caps:type_name -> mecharion.agent.v1.Capability
	26, // 1: mecharion.agent.v1.RegisterRequest.labels:type_name -> mecharion.agent.v1.RegisterRequest.LabelsEntry
	27, // 2: mecharion.agent.v1.Capability.detail:type_name -> mecharion.agent.v1.Capability.DetailEntry
	5,  // 3: mecharion.agent.v1.Assignment.specs:type_name -> mecharion.agent.v1.ResolvedSpecEnvelope
	28, // 4: mecharion.agent.v1.ResolvedSpecEnvelope.secrets:type_name -> mecharion.agent.v1.ResolvedSpecEnvelope.SecretsEntry
	12, // 5: mecharion.agent.v1.ReportRequest.instances:type_name -> mecharion.agent.v1.InstanceStatus
	18, // 6: mecharion.agent.v1.ReportRequest.facts:type_name -> mecharion.agent.v1.NodeFacts
	13, // 7: mecharion.agent.v1.ReportRequest.orphan_records:type_name -> mecharion.agent.v1.OrphanRecord
	14, // 8: mecharion.agent.v1.InstanceStatus.workload:type_name -> mecharion.agent.v1.WorkloadStatus
	15, // 9: mecharion.agent.v1.InstanceStatus.health:type_name -> mecharion.agent.v1.HealthStatus
	16, // 10: mecharion.agent.v1.InstanceStatus.resources:type_name -> mecharion.agent.v1.ResourceStatus
	17, // 11: mecharion.agent.v1.InstanceStatus.suppressed:type_name -> mecharion.agent.v1.SuppressedDrift
	21, // 12: mecharion.agent.v1.PushEventsRequest.events:type_name -> mecharion.agent.v1.Event
	0,  // 13: mecharion.agent.v1.Agent.Register:input_type -> mecharion.agent.v1.RegisterRequest
	3,  // 14: mecharion.agent.v1.Agent.Subscribe:input_type -> mecharion.agent.v1.SubscribeRequest
	10, // 15: mecharion.agent.v1.Agent.Report:input_type -> mecharion.agent.v1.ReportRequest
	19, // 16: mecharion.agent.v1.Agent.PushEvents:input_type -> mecharion.agent.v1.PushEventsRequest
	22, // 17: mecharion.agent.v1.Agent.FetchBlob:input_type -> mecharion.agent.v1.FetchBlobRequest
	24, // 18: mecharion.agent.v1.Agent.RenewCert:input_type -> mecharion.agent.v1.RenewCertRequest
	6,  // 19: mecharion.agent.v1.Agent.Tasks:input_type -> mecharion.agent.v1.TasksRequest
	8,  // 20: mecharion.agent.v1.Agent.ReportTaskResult:input_type -> mecharion.agent.v1.TaskResultRequest
	1,  // 21: mecharion.agent.v1.Agent.Register:output_type -> mecharion.agent.v1.RegisterResponse
	4,  // 22: mecharion.agent.v1.Agent.Subscribe:output_type -> mecharion.agent.v1.Assignment
	11, // 23: mecharion.agent.v1.Agent.Report:output_type -> mecharion.agent.v1.ReportResponse
	20, // 24: mecharion.agent.v1.Agent.PushEvents:output_type -> mecharion.agent.v1.PushEventsResponse
	23, // 25: mecharion.agent.v1.Agent.FetchBlob:output_type -> mecharion.agent.v1.BlobChunk
	25, // 26: mecharion.agent.v1.Agent.RenewCert:output_type -> mecharion.agent.v1.RenewCertResponse
	7,  // 27: mecharion.agent.v1.Agent.Tasks:output_type -> mecharion.agent.v1.Task
	9,  // 28: mecharion.agent.v1.Agent.ReportTaskResult:output_type -> mecharion.agent.v1.TaskResultResponse
	21, // [21:29] is the sub-list for method output_type
	13, // [13:21] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_mecharion_agent_v1_agent_proto_init() }
func file_mecharion_agent_v1_agent_proto_init() {
	if File_mecharion_agent_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mecharion_agent_v1_agent_proto_rawDesc), len(file_mecharion_agent_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mecharion_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_mecharion_agent_v1_agent_proto_depIdxs,
		MessageInfos:      file_mecharion_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_mecharion_agent_v1_agent_proto = out.File
	file_mecharion_agent_v1_agent_proto_goTypes = nil
	file_mecharion_agent_v1_agent_proto_depIdxs = nil
}
