// Package mecharion.agent.v1 是 mechd 与 mechlet 之间的协议。
//
// 设计见 docs/design/17-protocol.md 与 ADR-0029。
//
// **包名带大版本**：不兼容变更换包名（v2），两版可并存，因而控制面与 agent
// 可以分别升级——多节点场景下「先升哪个」必须是运维自己能决定的事。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.0
// source: mecharion/agent/v1/agent.proto

package agentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Agent_Register_FullMethodName         = "/mecharion.agent.v1.Agent/Register"
	Agent_Subscribe_FullMethodName        = "/mecharion.agent.v1.Agent/Subscribe"
	Agent_Report_FullMethodName           = "/mecharion.agent.v1.Agent/Report"
	Agent_PushEvents_FullMethodName       = "/mecharion.agent.v1.Agent/PushEvents"
	Agent_FetchBlob_FullMethodName        = "/mecharion.agent.v1.Agent/FetchBlob"
	Agent_RenewCert_FullMethodName        = "/mecharion.agent.v1.Agent/RenewCert"
	Agent_Tasks_FullMethodName            = "/mecharion.agent.v1.Agent/Tasks"
	Agent_ReportTaskResult_FullMethodName = "/mecharion.agent.v1.Agent/ReportTaskResult"
)

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Agent 是 mechlet 拨向 mechd 的服务。
//
// **mechlet 主动拨出**，节点上零入站端口。反过来（mechd 连 mechlet）要求
// 每台机器开一个入站端口，与那条约束直接冲突。
type AgentClient interface {
	// Register 交换版本与节点能力，换取会话。
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Subscribe 是服务端流：mechlet 拨出后挂住，mechd 按需推送规格。
	//
	// 不用双向流：上报与下发的失败模式不同，一条流上一次上报失败会连带
	// 撕掉下发通道。分开之后，心跳丢几个包不影响正在进行的部署。
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Assignment], error)
	// Report 上报观测状态（高频小包）。
	Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error)
	// PushEvents 补报断连期间缓冲的事件。
	PushEvents(ctx context.Context, in *PushEventsRequest, opts ...grpc.CallOption) (*PushEventsResponse, error)
	// FetchBlob 按 sha256 取载荷，分块流式返回。
	FetchBlob(ctx context.Context, in *FetchBlobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BlobChunk], error)
	// RenewCert 用**当前仍然有效的证书**换一张新的。
	//
	// 不需要 join token——现有证书就是身份证明。方向与 join 相反：
	// join 是「还没有身份的机器要一个」，续期是「已有身份的机器换一张」。
	//
	// 它挂在 Agent service 上而不是那个不带证书的 join 入口，正是因为
	// 它**必须**带证书：一台连不出有效证书的机器要走重新加入。
	RenewCert(ctx context.Context, in *RenewCertRequest, opts ...grpc.CallOption) (*RenewCertResponse, error)
	// Tasks 是 **ad-hoc 命令**通道：restart / exec / logs 走它。
	//
	// **与 Subscribe 分开是刻意的**（ADR-0038）。两者的分界是「丢一次会
	// 怎样」：
	//
	//	期望状态  丢了无所谓，下一轮重新确认；断连三天回来照做仍然正确
	//	命令      丢了就是没执行，必须告诉人；断连三天回来**不该补做**
	//
	// 放在同一条流上，第一次「顺手加个字段」就会开始侵蚀断连自治——而
	// Assignment 的纯净正是 mechlet 能在断连时工作的地基。
	//
	// 命令流断了不影响下发，反之亦然，与「不用双向流」是同一条理由。
	Tasks(ctx context.Context, in *TasksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Task], error)
	// ReportTaskResult 回报一条命令的执行结果。
	//
	// 单独一条上行 RPC 而不是搭 Report 的便车：Report 是周期性的观测快照
	// （默认 15 秒一次），而命令的结果**必须立刻回去**——敲命令的人正在
	// 终端前等着。
	ReportTaskResult(ctx context.Context, in *TaskResultRequest, opts ...grpc.CallOption) (*TaskResultResponse, error)
}

type agentClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentClient(cc grpc.ClientConnInterface) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, Agent_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Assignment], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Agent_ServiceDesc.Streams[0], Agent_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, Assignment]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_SubscribeClient = grpc.ServerStreamingClient[Assignment]

func (c *agentClient) Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, Agent_Report_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) PushEvents(ctx context.Context, in *PushEventsRequest, opts ...grpc.CallOption) (*PushEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushEventsResponse)
	err := c.cc.Invoke(ctx, Agent_PushEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) FetchBlob(ctx context.Context, in *FetchBlobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BlobChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Agent_ServiceDesc.Streams[1], Agent_FetchBlob_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FetchBlobRequest, BlobChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_FetchBlobClient = grpc.ServerStreamingClient[BlobChunk]

func (c *agentClient) RenewCert(ctx context.Context, in *RenewCertRequest, opts ...grpc.CallOption) (*RenewCertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewCertResponse)
	err := c.cc.Invoke(ctx, Agent_RenewCert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Tasks(ctx context.Context, in *TasksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Task], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Agent_ServiceDesc.Streams[2], Agent_Tasks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TasksRequest, Task]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_TasksClient = grpc.ServerStreamingClient[Task]

func (c *agentClient) ReportTaskResult(ctx context.Context, in *TaskResultRequest, opts ...grpc.CallOption) (*TaskResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResultResponse)
	err := c.cc.Invoke(ctx, Agent_ReportTaskResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
// All implementations must embed UnimplementedAgentServer
// for forward compatibility.
//
// Agent 是 mechlet 拨向 mechd 的服务。
//
// **mechlet 主动拨出**，节点上零入站端口。反过来（mechd 连 mechlet）要求
// 每台机器开一个入站端口，与那条约束直接冲突。
type AgentServer interface {
	// Register 交换版本与节点能力，换取会话。
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Subscribe 是服务端流：mechlet 拨出后挂住，mechd 按需推送规格。
	//
	// 不用双向流：上报与下发的失败模式不同，一条流上一次上报失败会连带
	// 撕掉下发通道。分开之后，心跳丢几个包不影响正在进行的部署。
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Assignment]) error
	// Report 上报观测状态（高频小包）。
	Report(context.Context, *ReportRequest) (*ReportResponse, error)
	// PushEvents 补报断连期间缓冲的事件。
	PushEvents(context.Context, *PushEventsRequest) (*PushEventsResponse, error)
	// FetchBlob 按 sha256 取载荷，分块流式返回。
	FetchBlob(*FetchBlobRequest, grpc.ServerStreamingServer[BlobChunk]) error
	// RenewCert 用**当前仍然有效的证书**换一张新的。
	//
	// 不需要 join token——现有证书就是身份证明。方向与 join 相反：
	// join 是「还没有身份的机器要一个」，续期是「已有身份的机器换一张」。
	//
	// 它挂在 Agent service 上而不是那个不带证书的 join 入口，正是因为
	// 它**必须**带证书：一台连不出有效证书的机器要走重新加入。
	RenewCert(context.Context, *RenewCertRequest) (*RenewCertResponse, error)
	// Tasks 是 **ad-hoc 命令**通道：restart / exec / logs 走它。
	//
	// **与 Subscribe 分开是刻意的**（ADR-0038）。两者的分界是「丢一次会
	// 怎样」：
	//
	//	期望状态  丢了无所谓，下一轮重新确认；断连三天回来照做仍然正确
	//	命令      丢了就是没执行，必须告诉人；断连三天回来**不该补做**
	//
	// 放在同一条流上，第一次「顺手加个字段」就会开始侵蚀断连自治——而
	// Assignment 的纯净正是 mechlet 能在断连时工作的地基。
	//
	// 命令流断了不影响下发，反之亦然，与「不用双向流」是同一条理由。
	Tasks(*TasksRequest, grpc.ServerStreamingServer[Task]) error
	// ReportTaskResult 回报一条命令的执行结果。
	//
	// 单独一条上行 RPC 而不是搭 Report 的便车：Report 是周期性的观测快照
	// （默认 15 秒一次），而命令的结果**必须立刻回去**——敲命令的人正在
	// 终端前等着。
	ReportTaskResult(context.Context, *TaskResultRequest) (*TaskResultResponse, error)
	mustEmbedUnimplementedAgentServer()
}

// UnimplementedAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServer struct{}

func (UnimplementedAgentServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAgentServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Assignment]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedAgentServer) Report(context.Context, *ReportRequest) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Report not implemented")
}
func (UnimplementedAgentServer) PushEvents(context.Context, *PushEventsRequest) (*PushEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PushEvents not implemented")
}
func (UnimplementedAgentServer) FetchBlob(*FetchBlobRequest, grpc.ServerStreamingServer[BlobChunk]) error {
	return status.Error(codes.Unimplemented, "method FetchBlob not implemented")
}
func (UnimplementedAgentServer) RenewCert(context.Context, *RenewCertRequest) (*RenewCertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewCert not implemented")
}
func (UnimplementedAgentServer) Tasks(*TasksRequest, grpc.ServerStreamingServer[Task]) error {
	return status.Error(codes.Unimplemented, "method Tasks not implemented")
}
func (UnimplementedAgentServer) ReportTaskResult(context.Context, *TaskResultRequest) (*TaskResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportTaskResult not implemented")
}
func (UnimplementedAgentServer) mustEmbedUnimplementedAgentServer() {}
func (UnimplementedAgentServer) testEmbeddedByValue()               {}

// UnsafeAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServer will
// result in compilation errors.
type UnsafeAgentServer interface {
	mustEmbedUnimplementedAgentServer()
}

func RegisterAgentServer(s grpc.ServiceRegistrar, srv AgentServer) {
	// If the following call panics, it indicates UnimplementedAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Agent_ServiceDesc, srv)
}

func _Agent_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, Assignment]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_SubscribeServer = grpc.ServerStreamingServer[Assignment]

func _Agent_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Report(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_Report_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Report(ctx, req.(*ReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_PushEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).PushEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_PushEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).PushEvents(ctx, req.(*PushEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_FetchBlob_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchBlobRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServer).FetchBlob(m, &grpc.GenericServerStream[FetchBlobRequest, BlobChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_FetchBlobServer = grpc.ServerStreamingServer[BlobChunk]

func _Agent_RenewCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).RenewCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_RenewCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).RenewCert(ctx, req.(*RenewCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Tasks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TasksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServer).Tasks(m, &grpc.GenericServerStream[TasksRequest, Task]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_TasksServer = grpc.ServerStreamingServer[Task]

func _Agent_ReportTaskResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ReportTaskResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ReportTaskResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ReportTaskResult(ctx, req.(*TaskResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Agent_ServiceDesc is the grpc.ServiceDesc for Agent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Agent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mecharion.agent.v1.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Agent_Register_Handler,
		},
		{
			MethodName: "Report",
			Handler:    _Agent_Report_Handler,
		},
		{
			MethodName: "PushEvents",
			Handler:    _Agent_PushEvents_Handler,
		},
		{
			MethodName: "RenewCert",
			Handler:    _Agent_RenewCert_Handler,
		},
		{
			MethodName: "ReportTaskResult",
			Handler:    _Agent_ReportTaskResult_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _Agent_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FetchBlob",
			Handler:       _Agent_FetchBlob_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Tasks",
			Handler:       _Agent_Tasks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mecharion/agent/v1/agent.proto",
}
